import { BANK } from "./problems";

export type TrackId = "math" | "physics" | "advanced";

export type VisualKind =
  | "percent"
  | "equation"
  | "lineplot"
  | "expplot"
  | "unitcircle"
  | "area"
  | "sequence"
  | "limitplot"
  | "tangent"
  | "integral"
  | "dice"
  | "vector"
  | "units"
  | "motion1d"
  | "projectile"
  | "forces"
  | "energy"
  | "collision"
  | "wave"
  | "pendulum"
  | "fluid"
  | "circuit"
  | "charges"
  | "lens"
  | "photon"
  | "argand"
  | "series"
  | "surface"
  | "field"
  | "fourier"
  | "laplace"
  | "ode"
  | "variation"
  | "newtonplot"
  | "legendre"
  | "poisson";

export type Topic = {
  id: string;
  track: TrackId;
  title: string;
  blurb: string;
  chapter?: string;
  minutes: number;
  level: "dasar" | "menengah" | "lanjut";
  promise: string;
  oneIdea: string;
  ideas: { t: string; d: string }[];
  formulas: { name: string; tex: string; when: string }[];
  visual: VisualKind;
  caseTitle: string;
  casePlace: string;
  caseStory: string;
  caseMove: string[];
  caseTake: string;
  traps: { bad: string; fix: string }[];
  howTo: string[];
  check: { q: string; a: string; why: string };
  related: string;
};

const topics: Topic[] = [
  {
    id: "bilangan",
    track: "math",
    title: "Persen, rasio, urutan",
    blurb: "Diskon, bagi rata, dan perangkap dua persen beruntun.",
    minutes: 10,
    level: "dasar",
    promise: "Kamu bisa menghitung harga akhir tanpa menebak.",
    oneIdea: "Persen artinya per seratus. Ubah dulu jadi desimal, baru dikali.",
    ideas: [
      { t: "Dari persen ke desimal", d: "20% = 0,20. Geser koma dua langkah ke kiri." },
      { t: "Rasio adalah bagian", d: "2:3 berarti 2 bagian dan 3 bagian. Total ada 5 bagian." },
      { t: "Urutan hitung", d: "Kurung dulu, lalu kali dan bagi, baru tambah dan kurang." },
    ],
    formulas: [
      { name: "p% dari N", tex: "\\dfrac{p}{100}\\times N", when: "Pajak, diskon, kadar." },
      { name: "Harga setelah diskon", tex: "H\\left(1-\\dfrac{d}{100}\\right)", when: "Satu kali diskon." },
      { name: "Dua diskon beruntun", tex: "H\\left(1-\\dfrac{d_1}{100}\\right)\\left(1-\\dfrac{d_2}{100}\\right)", when: "Promo bertumpuk. Jangan jumlahkan persen." },
    ],
    visual: "percent",
    caseTitle: "Flash sale yang kelihatan 50%",
    casePlace: "Keranjang belanja",
    caseStory: "Jaket Rp200.000 diskon 30%, lalu kupon 20%. Otak ingin bilang diskon 50%, jadi Rp100.000. Itu jebakan.",
    caseMove: [
      "Hitung 30% dulu: 0,70 × 200.000 = 140.000.",
      "Kupon 20% kena harga yang sudah turun: 0,80 × 140.000 = 112.000.",
      "Diskon total efektif (200−112)/200 = 44%, bukan 50%.",
    ],
    caseTake: "Persen kedua selalu menghitung dari sisa, bukan dari harga awal.",
    traps: [
      { bad: "30% + 20% = 50%.", fix: "Kalikan faktor 0,70 dan 0,80." },
      { bad: "Naik 20% lalu turun 20% kembali ke awal.", fix: "1,20 × 0,80 = 0,96. Masih kurang 4%." },
    ],
    howTo: [
      "Tulis ulang soal jadi kalimat: berapa dari berapa.",
      "Ubah semua persen jadi desimal sebelum menyentuh kalkulator.",
      "Setelah 3 soal, tutup catatan dan hitung satu diskon beruntun dari ingatan.",
    ],
    check: {
      q: "Harga 100 naik 10% lalu turun 10%. Apa hasilnya 100?",
      a: "Tidak. Hasilnya 99.",
      why: "100 × 1,1 × 0,9 = 99. Dua persen yang sama tidak saling menghapus.",
    },
    related: "aljabar",
  },
  {
    id: "aljabar",
    track: "math",
    title: "Persamaan linear",
    blurb: "Huruf sebagai kotak angka. Seimbangkan dua ruas.",
    minutes: 12,
    level: "dasar",
    promise: "Kamu bisa membuka x tanpa mencoba-coba selamanya.",
    oneIdea: "Apa yang kamu lakukan di ruas kiri, lakukan juga di ruas kanan.",
    ideas: [
      { t: "x adalah angka yang belum dibuka", d: "Bukan benda ajaib. Satu kotak, satu isi, di persamaan linear sederhana." },
      { t: "Pindah ruas = operasi lawan", d: "Yang ditambah, dikurangi. Yang dikali, dibagi." },
      { t: "Dua persamaan", d: "Jumlahkan atau kurangkan supaya satu huruf hilang." },
    ],
    formulas: [
      { name: "Satu langkah", tex: "ax+b=c \\Rightarrow x=\\dfrac{c-b}{a}", when: "a tidak nol." },
      { name: "Sistem jumlah-selisih", tex: "x=\\dfrac{(x+y)+(x-y)}{2}", when: "Dua persamaan rapi." },
      { name: "Cek", tex: "ax+b \\stackrel{?}{=} c", when: "Selalu, 10 detik, sebelum percaya." },
    ],
    visual: "equation",
    caseTitle: "Tarif ojek yang terasa mahal",
    casePlace: "Perjalanan 7 km",
    caseStory: "Aplikasi mematok buka Rp8.000 ditambah Rp3.000 per km. Kamu bayar Rp29.000 dan ingin tahu jaraknya benar.",
    caseMove: [
      "Tulis 8000 + 3000x = 29000.",
      "Kurangi 8000: 3000x = 21000.",
      "Bagi 3000: x = 7 km. Tagihan sesuai jarak.",
    ],
    caseTake: "Model linear cukup untuk tarif tetap + tarif per satuan.",
    traps: [
      { bad: "Membagi hanya satu suku.", fix: "Bagi seluruh ruas, atau pindahkan suku dulu." },
      { bad: "Lupa tanda minus saat pindah ruas.", fix: "Ubah operasi, jangan hanya memindahkan simbol." },
    ],
    howTo: [
      "Satu baris, satu operasi. Jangan loncat di kepala.",
      "Lingkari suku yang mengandung x supaya mata tidak kabur.",
      "Selalu substitusi balik. Itu bukan kerja tambahan, itu kunci jawabannya.",
    ],
    check: {
      q: "Dari 2x = 10, apa x = 5 atau x = 8?",
      a: "x = 5.",
      why: "Bagi kedua ruas dengan 2. Cek: 2×5 = 10.",
    },
    related: "fungsi",
  },
  {
    id: "fungsi",
    track: "math",
    title: "Fungsi dan grafik",
    blurb: "Mesin masukan-keluaran, dan kemiringan garis.",
    minutes: 12,
    level: "dasar",
    promise: "Kamu bisa membaca grafik seperti membaca tarif.",
    oneIdea: "Fungsi adalah mesin: satu masukan, tepat satu keluaran. Grafik adalah semua pasangan itu.",
    ideas: [
      { t: "Masukkan, keluarkan", d: "f(3) artinya ganti x dengan 3, lalu hitung." },
      { t: "Gradien", d: "Naik dibanding maju. Positif menanjak ke kanan." },
      { t: "Titik potong", d: "c pada y = mx + c adalah nilai saat x = 0." },
    ],
    formulas: [
      { name: "Garis", tex: "f(x)=mx+c", when: "Perubahan konstan." },
      { name: "Gradien dua titik", tex: "m=\\dfrac{y_2-y_1}{x_2-x_1}", when: "Ada dua pembacaan." },
      { name: "Parabola sederhana", tex: "f(x)=ax^2", when: "Perubahan yang makin cepat." },
    ],
    visual: "lineplot",
    caseTitle: "Tarif taksi di kertas",
    casePlace: "Argometer",
    caseStory: "Taksi di satu kota: bendera Rp7.000, lalu Rp4.000 per km. Grafiknya garis lurus yang tidak lewat titik nol.",
    caseMove: [
      "Tulis f(x) = 4000x + 7000.",
      "Gradien 4000 = tambahan tiap km.",
      "Untuk 5 km: 4000×5 + 7000 = 27.000.",
    ],
    caseTake: "Gradien adalah harga per satuan. Titik potong adalah biaya tetap.",
    traps: [
      { bad: "f(x+1) sama dengan f(x)+1.", fix: "Masukkan seluruh kurung ke mesin." },
      { bad: "Gradien = y/x untuk setiap garis.", fix: "Itu hanya jika garis lewat (0,0)." },
    ],
    howTo: [
      "Gambar sumbu kecil di sudut kertas sebelum rumus.",
      "Hitung dua titik, baru hubungkan. Jangan mengarang bentuk.",
      "Ubah gradien di visual, ucapkan satu kalimat: garis makin curam atau landai.",
    ],
    check: {
      q: "f(x)=2x+1. f(4) berapa?",
      a: "9.",
      why: "2×4 + 1 = 9. Bukan 2×4+1 yang dibiarkan menggantung.",
    },
    related: "turunan",
  },
  {
    id: "eksponen",
    track: "math",
    title: "Eksponen dan logaritma",
    blurb: "Pertumbuhan berulang, dan pertanyaan dibaliknya.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa membedakan kali, tambah, dan pangkat.",
    oneIdea: "Pangkat menghitung pengulangan kali. Logaritma bertanya: diulang berapa kali?",
    ideas: [
      { t: "Bukan perkalian biasa", d: "2^5 = 32, sedangkan 2×5 = 10." },
      { t: "Sifat perkalian pangkat", d: "Basis sama: pangkat ditambah saat dikali." },
      { t: "Log adalah kebalikan", d: "log₂ 32 = 5 karena 2^5 = 32." },
    ],
    formulas: [
      { name: "Perkalian", tex: "a^m a^n = a^{m+n}", when: "Basis sama." },
      { name: "Definisi log", tex: "\\log_b (b^k)=k", when: "Basis positif, bukan 1." },
      { name: "Lipat ganda", tex: "N(t)=N_0\\,2^{t/T}", when: "Populasi atau bunga yang menggandakan." },
    ],
    visual: "expplot",
    caseTitle: "Bakteri di suhu dapur",
    casePlace: "Nasi yang lupa masuk kulkas",
    caseStory: "Satu koloni 100 bakteri menggandakan diri tiap jam pada suhu ruang. Setelah 5 jam, jumlahnya bukan 100+5.",
    caseMove: [
      "Tiap jam ×2, sebanyak 5 kali.",
      "2^5 = 32.",
      "100 × 32 = 3.200 bakteri. Makanya makanan basi cepat sekali, bukan linear.",
    ],
    caseTake: "Hal yang menggandakan terasa pelan di awal dan meledak kemudian.",
    traps: [
      { bad: "a^m + a^n = a^{m+n}.", fix: "Penjumlahan pangkat tidak digabung begitu." },
      { bad: "(a+b)^2 = a^2 + b^2.", fix: "Ada suku 2ab." },
    ],
    howTo: [
      "Tulis perkalian panjang untuk pangkat kecil sampai polanya nempel.",
      "Setiap soal log, terjemahkan jadi kalimat berpangkat.",
      "Di visual, geser waktu dan sebut kapan grafik meninggalkan garis lurus.",
    ],
    check: {
      q: "2^3 × 2^2 sama dengan 2 pangkat berapa?",
      a: "5.",
      why: "Basis sama, pangkat dijumlah: 3+2.",
    },
    related: "deret",
  },
  {
    id: "trig",
    track: "math",
    title: "Trigonometri",
    blurb: "Lingkaran satuan, segitiga siku, tinggi yang tak terukur.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa mengukur tinggi tanpa memanjatnya.",
    oneIdea: "Sinus dan kosinus adalah koordinat titik yang berjalan di lingkaran satuan.",
    ideas: [
      { t: "Segitiga siku", d: "sin = depan/miring, cos = samping/miring, tan = depan/samping." },
      { t: "Lingkaran", d: "Pada lingkaran jari-jari 1, x = cos, y = sin." },
      { t: "Sudut istimewa", d: "30°, 45°, 60° cukup untuk sebagian besar latihan awal." },
    ],
    formulas: [
      { name: "Definisi", tex: "\\sin\\theta=\\dfrac{\\text{depan}}{\\text{miring}}", when: "Segitiga siku-siku." },
      { name: "Identitas", tex: "\\sin^2\\theta+\\cos^2\\theta=1", when: "Menghubungkan sin dan cos." },
      { name: "Tinggi", tex: "h = d\\tan\\theta", when: "Jarak datar dan sudut elevasi diketahui." },
    ],
    visual: "unitcircle",
    caseTitle: "Estimasi tinggi pohon di halaman",
    casePlace: "Halaman sekolah",
    caseStory: "Kamu berdiri 20 m dari pohon. Clinometer menunjukkan 30° ke pucuk. Tanahnya datar.",
    caseMove: [
      "Gambar siku-siku: samping 20 m, sudut 30°.",
      "tinggi = 20 × tan 30°.",
      "tan 30° ≈ 0,577, jadi tinggi ≈ 11,5 m. Tambahkan tinggi mata kalau alat tidak di tanah.",
    ],
    caseTake: "Tan menjawab depan dibanding samping. Sin dan cos butuh sisi miring.",
    traps: [
      { bad: "Kalkulator dalam radian padahal soal derajat.", fix: "Cek mode sebelum menekan sin." },
      { bad: "Pakai sin untuk tinggi kalau yang diketahui jarak datar.", fix: "Jarak datar adalah sisi samping: pakai tan." },
    ],
    howTo: [
      "Gambar segitiga dulu, beri label depan-samping-miring relatif terhadap sudut yang dipakai.",
      "Hafal hanya 30-45-60. Sisanya kalkulator.",
      "Putar sudut di lingkaran dan sebut: sin adalah tinggi titik, cos adalah gesernya.",
    ],
    check: {
      q: "sin 30° bernilai?",
      a: "0,5.",
      why: "Setengah. Ini jangkar hafalan yang paling sering dipakai.",
    },
    related: "geometri",
  },
  {
    id: "geometri",
    track: "math",
    title: "Luas, keliling, Pythagoras",
    blurb: "Bedakan tutupan dan pinggir. Ukur diagonal.",
    minutes: 10,
    level: "dasar",
    promise: "Kamu berhenti menukar luas dengan keliling.",
    oneIdea: "Luas mengukur tutupan. Keliling mengukur pinggir. Keduanya tidak saling mengganti.",
    ideas: [
      { t: "Satuan memberitahu", d: "m² adalah luas. m adalah panjang." },
      { t: "Segitiga", d: "Setengah jajargenjang dengan alas dan tinggi yang sama." },
      { t: "Siku-siku", d: "Sisi terpanjang adalah hipotenusa, di seberang sudut siku." },
    ],
    formulas: [
      { name: "Segitiga", tex: "L=\\dfrac{1}{2}ah", when: "Tinggi tegak lurus alas." },
      { name: "Lingkaran", tex: "L=\\pi r^2,\\quad K=2\\pi r", when: "Jangan tertukar." },
      { name: "Pythagoras", tex: "a^2+b^2=c^2", when: "Hanya segitiga siku-siku." },
    ],
    visual: "area",
    caseTitle: "Keramik dan kabel diagonal",
    casePlace: "Kamar 4 m × 3 m",
    caseStory: "Kamu membeli keramik untuk lantai, dan juga kabel untuk menarik dari pojok ke pojok.",
    caseMove: [
      "Luas lantai = 4 × 3 = 12 m². Itu untuk keramik.",
      "Keliling = 14 m. Itu untuk lis, bukan lantai.",
      "Diagonal = √(16+9) = 5 m. Kabel lurus butuh 5 m, bukan 7 m.",
    ],
    caseTake: "Tanyakan dulu: yang diukur tutupan, pinggir, atau potongan miring?",
    traps: [
      { bad: "Keliling lingkaran = πr².", fix: "Itu luas. Keliling 2πr." },
      { bad: "Pythagoras untuk semua segitiga.", fix: "Harus ada sudut 90°." },
    ],
    howTo: [
      "Tulis satuan di jawaban. Salah satuan = salah makna.",
      "Sketsa kecil, arsir yang ditanyakan.",
      "Untuk lingkaran, lingkari kata luas atau keliling di soal sebelum rumus.",
    ],
    check: {
      q: "Lingkaran jari-jari 1. Kelilingnya 2π atau π?",
      a: "2π.",
      why: "Keliling = 2πr. πr² adalah luas, di sini juga π, kebetulan angka mirip.",
    },
    related: "trig",
  },
  {
    id: "barisan",
    track: "math",
    title: "Barisan dan deret",
    blurb: "Tambah tetap atau kali tetap, lalu jumlahkan.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa melihat cicilan dan pertumbuhan sebagai pola.",
    oneIdea: "Aritmetika menambah angka yang sama. Geometri mengalikan angka yang sama.",
    ideas: [
      { t: "Suku vs jumlah", d: "U_n satu angka dalam barisan. S_n jumlah sampai suku itu." },
      { t: "Beda dan rasio", d: "Beda ditambah. Rasio dikali." },
      { t: "Tak hingga", d: "Jumlah tak hingga geometri hanya aman jika pengali mutlaknya kurang dari 1." },
    ],
    formulas: [
      { name: "Suku aritmetika", tex: "U_n=a+(n-1)d", when: "Pola tambah tetap." },
      { name: "Jumlah aritmetika", tex: "S_n=\\dfrac{n}{2}\\big(2a+(n-1)d\\big)", when: "Menjumlah banyak suku." },
      { name: "Geometri tak hingga", tex: "S=\\dfrac{a}{1-r},\\ |r|<1", when: "Pantulan, cicilan bunga tertentu, deret sisa." },
    ],
    visual: "sequence",
    caseTitle: "Tabungan mingguan",
    casePlace: "Celengan",
    caseStory: "Minggu pertama menabung Rp10.000, lalu tiap minggu menambah Rp5.000. Kamu ingin tahu minggu ke-8, bukan jumlah seluruhnya.",
    caseMove: [
      "a = 10000, d = 5000, n = 8.",
      "U_8 = 10000 + 7×5000.",
      "U_8 = 45.000. Kalau yang ditanya total, pakai S_n, hasilnya lain.",
    ],
    caseTake: "Baca kata kunci: suku ke-n atau jumlah n suku.",
    traps: [
      { bad: "Memakai n, bukan n−1, pada beda.", fix: "Dari suku 1 ke suku n ada (n−1) langkah." },
      { bad: "Menjumlah geometri |r|≥1 sampai tak hingga.", fix: "Deret itu tidak konvergen." },
    ],
    howTo: [
      "Tulis 4 suku pertama dengan tangan. Pola lebih jelas daripada rumus.",
      "Tandai di soal: yang dicari U atau S.",
      "Di visual, geser beda sampai kamu bisa menebak suku berikutnya sebelum grafik bergerak.",
    ],
    check: {
      q: "Barisan 3, 7, 11. Beda dan suku ke-4?",
      a: "Beda 4, suku ke-4 adalah 15.",
      why: "11+4. Langkah dari suku pertama: 3 langkah beda untuk sampai ke suku ke-4.",
    },
    related: "deret",
  },
  {
    id: "limit",
    track: "math",
    title: "Limit",
    blurb: "Nilai yang didekati, termasuk saat substitusi macet.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu tidak panik ketika melihat 0/0.",
    oneIdea: "Limit adalah angka yang didekati, bukan selalu angka yang bisa langsung dipasang.",
    ideas: [
      { t: "Substitusi dulu", d: "Polinom jinak: masukkan angkanya." },
      { t: "0/0 bukan jawaban", d: "Itu tanda bentuk belum sederhana." },
      { t: "Arti fisis", d: "Kecepatan sesaat adalah limit kecepatan rata-rata pada selang yang mengecil." },
    ],
    formulas: [
      { name: "Polinom", tex: "\\lim_{x\\to a} p(x)=p(a)", when: "p polinom." },
      { name: "Selisih kuadrat", tex: "\\lim_{x\\to a}\\dfrac{x^2-a^2}{x-a}=2a", when: "Setelah difaktorkan." },
      { name: "Definisi turunan", tex: "f'(a)=\\lim_{h\\to 0}\\dfrac{f(a+h)-f(a)}{h}", when: "Menghubungkan limit dan kemiringan." },
    ],
    visual: "limitplot",
    caseTitle: "Speedometer dari dua titik GPS",
    casePlace: "Perjalanan motor",
    caseStory: "GPS memberi posisi tiap beberapa detik. Kecepatan rata-rata pada selang 10 detik kasar. Makin kecil selangnya, angkanya mendekati kecepatan sesaat.",
    caseMove: [
      "Kecepatan rata-rata = Δs / Δt.",
      "Kecilkan Δt. Kalau fungsinya mulus, hasilnya mendekati satu angka.",
      "Angka batas itu limit. Di kalkulus ia menjadi turunan posisi.",
    ],
    caseTake: "0/0 pada selang nol artinya kamu butuh penyederhanaan, bukan bahwa kecepatan nol atau tak hingga.",
    traps: [
      { bad: "Menulis jawaban 0/0.", fix: "Faktorkan atau uraikan, lalu substitusi lagi." },
      { bad: "Membagi nol begitu saja dan menyebut tak hingga.", fix: "Lihat tanda kiri dan kanan. Tidak selalu sama." },
    ],
    howTo: [
      "Substitusi dulu. Jika dapat angka biasa, selesai.",
      "Jika 0/0, coret faktor yang membuat nol.",
      "Di visual, dekati x=1 dari dua sisi dan baca apakah y menuju angka yang sama.",
    ],
    check: {
      q: "Limit x→2 dari (x²−4)/(x−2)?",
      a: "4.",
      why: "Faktorkan jadi x+2, lalu masukkan 2.",
    },
    related: "turunan",
  },
  {
    id: "turunan",
    track: "math",
    title: "Turunan",
    blurb: "Kemiringan sesaat. Seberapa cepat berubah sekarang.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa mengubah posisi menjadi kecepatan.",
    oneIdea: "Turunan adalah kemiringan pada satu titik, yaitu laju perubahan sesaat.",
    ideas: [
      { t: "Aturan pangkat", d: "Bawa pangkat jadi koefisien, lalu turunkan pangkat satu." },
      { t: "Jumlah", d: "Turunan jumlah adalah jumlah turunan. Kerjakan suku per suku." },
      { t: "Puncak", d: "Di banyak bukit mulus, kemiringan nol di puncak dan di lembah." },
    ],
    formulas: [
      { name: "Pangkat", tex: "\\dfrac{d}{dx} x^n = n x^{n-1}", when: "n bukan nol. Konstanta turunannya 0." },
      { name: "Kelipatan", tex: "(cf)'=c f'", when: "Angka konstanta keluar." },
      { name: "Posisi ke kecepatan", tex: "v=\\dfrac{ds}{dt}", when: "s posisi, t waktu." },
    ],
    visual: "tangent",
    caseTitle: "Biaya satu porsi tambahan",
    casePlace: "Warung makan",
    caseStory: "Biaya harian sebuah warung tidak linear: ada kompor yang makin boros saat porsi bertambah. Turunan biaya terhadap jumlah porsi adalah biaya marginal — ongkos satu porsi tambahan di tingkat produksi itu.",
    caseMove: [
      "Misalkan C(q) = 2 q² + 30, dalam ribu rupiah, q puluhan porsi.",
      "C'(q) = 4q.",
      "Saat q = 5, porsi tambahan menelan kira-kira 20 satuan biaya, bukan C(5) itu sendiri.",
    ],
    caseTake: "Turunan memberitahu tambahan, bukan nilai total.",
    traps: [
      { bad: "Turunan x² adalah x.", fix: "Adalah 2x." },
      { bad: "Mengalikan turunan saat fungsinya dijumlah.", fix: "Itu aturan kali, nanti. Untuk jumlah, jumlahkan saja." },
    ],
    howTo: [
      "Turunkan semua suku di kertas terpisah, baru gabung.",
      "Baru setelah itu masukkan angka.",
      "Di visual, geser titik dan lihat garis singgung menempel, bukan memotong sembarangan.",
    ],
    check: {
      q: "Turunan 5x³?",
      a: "15 x².",
      why: "Pangkat 3 turun ke depan, jadi 5×3 x².",
    },
    related: "integral",
  },
  {
    id: "integral",
    track: "math",
    title: "Integral",
    blurb: "Menjumlah irisan tipis. Luas di bawah grafik.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menjumlahkan perubahan yang terus-menerus.",
    oneIdea: "Integral menjumlahkan irisan sangat tipis. Luas di bawah grafik adalah jumlah itu.",
    ideas: [
      { t: "Kebalikan turunan", d: "Cari fungsi yang turunannya kembali ke soal. Tambahkan +C jika batas tidak ada." },
      { t: "Batas", d: "Integral tentu = antiturunan di batas atas dikurangi batas bawah." },
      { t: "Satuan luas", d: "Kalau sumbu horizontal waktu dan vertikal kecepatan, luasnya adalah jarak." },
    ],
    formulas: [
      { name: "Pangkat", tex: "\\int x^n\\,dx=\\dfrac{x^{n+1}}{n+1}+C", when: "n ≠ −1." },
      { name: "Tentu", tex: "\\int_a^b f=F(b)-F(a)", when: "F' = f." },
      { name: "Jarak", tex: "s=\\int v\\,dt", when: "v kecepatan terhadap waktu." },
    ],
    visual: "integral",
    caseTitle: "Jarak dari grafik speedometer",
    casePlace: "Perjalanan tol",
    caseStory: "Speedometer memberi kecepatan tiap saat. Jarak bukan kecepatan dikali waktu jika kecepatan berubah. Luas di bawah grafik v–t adalah jarak.",
    caseMove: [
      "Misalkan v = 2t m/s dari t=1 sampai t=4.",
      "Antiturunan t².",
      "Jarak = 16 − 1 = 15 m.",
    ],
    caseTake: "Kalikan hanya jika tingginya rata. Jika tidak, integralkan.",
    traps: [
      { bad: "Lupa membagi dengan pangkat baru.", fix: "Naikkan pangkat, lalu bagi pangkat itu." },
      { bad: "F(a) − F(b).", fix: "Urutannya atas dikurangi bawah." },
    ],
    howTo: [
      "Tulis antiturunan di tengah, batas di kanan. Tiga kolom kecil.",
      "Cek dengan menurunkan kembali. Harus kembali ke soal.",
      "Di visual, lebarkan batas dan lihat luas bertambah — itu arti penjumlahan.",
    ],
    check: {
      q: "Integral dari 0 sampai 2 untuk fungsi x?",
      a: "2.",
      why: "Antiturunan x²/2. Di 2 dapat 2, di 0 dapat 0.",
    },
    related: "lipat",
  },
  {
    id: "peluang",
    track: "math",
    title: "Peluang",
    blurb: "Yang diinginkan dibagi yang sama mungkin.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa menghitung peluang tanpa firasat.",
    oneIdea: "Peluang klasik = banyak cara yang kamu mau, dibagi banyak cara yang sama mungkin.",
    ideas: [
      { t: "Ruang sampel dulu", d: "Daftar atau hitung semua hasil sebelum memilih yang diinginkan." },
      { t: "Saling lepas", d: "Tidak bisa bersamaan: peluang dijumlah." },
      { t: "Tanpa urutan", d: "Kombinasi. Urutan beda yang isinya sama dihitung sekali." },
    ],
    formulas: [
      { name: "Klasik", tex: "P(A)=\\dfrac{n(A)}{n(S)}", when: "Hasil sama mungkin." },
      { name: "Tambah", tex: "P(A\\cup B)=P(A)+P(B)", when: "A dan B tidak tumpang tindih." },
      { name: "Kombinasi", tex: "C(n,k)=\\dfrac{n!}{k!(n-k)!}", when: "Memilih, urutan tidak penting." },
    ],
    visual: "dice",
    caseTitle: "Tes cepat dan kabar yang menakutkan",
    casePlace: "Hasil pemeriksaan",
    caseStory: "Sebuah penyakit langka hanya ada pada 1 dari 100 orang. Tesnya positif pada orang sakit, tetapi juga positif palsu pada 5 dari 100 orang sehat. Kabar positif belum berarti peluang sakit 95%.",
    caseMove: [
      "Bayangkan 100 orang: kira-kira 1 sakit, 99 sehat.",
      "Positif palsu kira-kira 5 orang sehat. Tambah 1 yang benar-benar sakit.",
      "Dari sekitar 6 kabar positif, hanya 1 yang sakit. Peluangnya dekat 1/6, bukan 95%.",
    ],
    caseTake: "Peluang butuh angka dasar (seberapa langka), bukan hanya akurasi iklan tes.",
    traps: [
      { bad: "Menjumlah peluang yang tumpang tindih.", fix: "Kurangi irisannya, atau pastikan saling lepas." },
      { bad: "Memakai permutasi padahal urutan tidak penting.", fix: "Bagi dengan k!." },
    ],
    howTo: [
      "Tulis n(S) di pojok sebelum menghitung n(A).",
      "Untuk dadu, 6 muka. Untuk dua dadu, 36 pasangan.",
      "Lempar di visual, bandingkan frekuensi dengan teori. Selisih kecil itu wajar.",
    ],
    check: {
      q: "Peluang dadu adil keluar genap?",
      a: "1/2.",
      why: "3 muka dari 6.",
    },
    related: "statistik",
  },
  {
    id: "vektor",
    track: "math",
    title: "Vektor",
    blurb: "Besar plus arah. Jangan dijumlah seperti saklar.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa menggabungkan dua perpindahan tanpa tersesat.",
    oneIdea: "Vektor punya besar dan arah. Menjumlahkannya seperti berjalan berurutan.",
    ideas: [
      { t: "Komponen", d: "Urai ke x dan y. Jumlahkan tiap sumbu sendiri." },
      { t: "Panjang", d: "Pythagoras pada komponen." },
      { t: "Dot", d: "Seberapa searah dua vektor. Nol jika tegak lurus." },
    ],
    formulas: [
      { name: "Panjang", tex: "|\\mathbf a|=\\sqrt{x^2+y^2}", when: "Dari komponen." },
      { name: "Dot", tex: "\\mathbf a\\cdot\\mathbf b=x_1 x_2+y_1 y_2", when: "Proyeksi, usaha, sudut." },
      { name: "Jumlah", tex: "(x_1+x_2,\\ y_1+y_2)", when: "Perpindahan berurutan." },
    ],
    visual: "vector",
    caseTitle: "Perahu menyeberang sungai",
    casePlace: "Sungai yang mengalir",
    caseStory: "Perahu diarahkan lurus ke seberang 2 m/s, arus sungai 1,5 m/s menyamping. Jalurnya tidak lurus ke seberang.",
    caseMove: [
      "Komponen: (0 ; 2) dari mesin, (1,5 ; 0) dari arus.",
      "Jumlah (1,5 ; 2).",
      "Kelajuan terhadap dasar ≈ √(2,25+4) ≈ 2,5 m/s, arah miring.",
    ],
    caseTake: "Arah haluan bukan selalu arah lintasan.",
    traps: [
      { bad: "Menjumlah panjang dua vektor sebagai panjang resultan.", fix: "Jumlahkan komponen, baru cari panjang." },
      { bad: "Dot product menghasilkan vektor.", fix: "Hasilnya bilangan." },
    ],
    howTo: [
      "Gambar anak panah, bukan hanya angka.",
      "Pisahkan sumbu dengan dua kolom: x dan y.",
      "Di lab 3D, putar pandangan. Resultan adalah diagonal perjalanan.",
    ],
    check: {
      q: "Panjang vektor (3, 4)?",
      a: "5.",
      why: "3-4-5.",
    },
    related: "matriks",
  },
  {
    id: "satuan",
    track: "physics",
    title: "Besaran dan satuan",
    blurb: "Angka tanpa satuan adalah teka-teki.",
    minutes: 8,
    level: "dasar",
    promise: "Kamu berhenti mencampur km/jam dengan m/s.",
    oneIdea: "Ubah dulu ke satu sistem, baru dihitung. Satuan adalah bagian dari jawaban.",
    ideas: [
      { t: "SI dulu", d: "meter, kilogram, sekon, ampere. Awalan kilo = 1000, mili = 0,001." },
      { t: "Kecepatan", d: "m/s ke km/jam kali 3,6. Sebaliknya bagi 3,6." },
      { t: "Dimensi", d: "Dua ruas persamaan harus satuan yang sama. Kalau tidak, ada yang salah." },
    ],
    formulas: [
      { name: "km/jam ke m/s", tex: "v_{\\mathrm{m/s}}=\\dfrac{v_{\\mathrm{km/jam}}}{3{,}6}", when: "Hampir semua soal gerak." },
      { name: "m/s ke km/jam", tex: "v_{\\mathrm{km/jam}}=3{,}6\\, v_{\\mathrm{m/s}}", when: "Membaca hasil ke bahasa sehari-hari." },
      { name: "Panjang", tex: "1\\ \\mathrm{m}=100\\ \\mathrm{cm}", when: "Jangan bagi 1000." },
    ],
    visual: "units",
    caseTitle: "Batas kecepatan yang disalahbaca",
    casePlace: "Rambu jalan",
    caseStory: "Mobil tercatat 20 m/s di alat. Pengemudi merasa pelan karena berpikir dalam km/jam.",
    caseMove: [
      "20 × 3,6 = 72.",
      "Jadi 72 km/jam.",
      "Di jalan perkotaan 40 km/jam, ini sudah terlalu cepat. Satuan mengubah keputusan.",
    ],
    caseTake: "Sebelum bereaksi pada angka, sebut satuannya keras-keras.",
    traps: [
      { bad: "1 m² = 100 cm².", fix: "1 m = 100 cm, jadi 1 m² = 10.000 cm²." },
      { bad: "Membagi 3,6 saat dari m/s ke km/jam.", fix: "Arah itu dikali." },
    ],
    howTo: [
      "Lingkari satuan di soal dengan warna yang sama untuk besaran yang sama.",
      "Konversi di baris pertama, sebelum rumus fisika.",
      "Cek dimensi di akhir: detik tidak boleh tiba-tiba jadi meter.",
    ],
    check: {
      q: "36 km/jam sama dengan berapa m/s?",
      a: "10.",
      why: "36/3,6 = 10.",
    },
    related: "kinematika",
  },
  {
    id: "kinematika",
    track: "physics",
    title: "Gerak lurus",
    blurb: "Kecepatan berubah rata, posisi mengikuti.",
    minutes: 12,
    level: "dasar",
    promise: "Kamu bisa menghitung kapan mobil berhenti.",
    oneIdea: "Percepatan tetap membuat kecepatan berubah secara merata. Posisi berubah semakin lama semakin banyak.",
    ideas: [
      { t: "Tiga rumus saudara", d: "Pilih yang tidak memuat besaran yang tidak diketahui." },
      { t: "Tanda", d: "Sepakat dulu arah positif. Perlambatan bisa berarti a negatif." },
      { t: "Waktu kuadrat", d: "Pada s, waktu muncul sebagai t dan t². Jangan hilangkan salah satu." },
    ],
    formulas: [
      { name: "Kecepatan", tex: "v=v_0+at", when: "a tetap, butuh waktu." },
      { name: "Posisi", tex: "s=v_0 t+\\tfrac{1}{2}at^2", when: "a tetap, dari posisi awal yang dijadikan nol." },
      { name: "Tanpa waktu", tex: "v^2=v_0^2+2as", when: "Waktu tidak ditanya dan tidak diketahui." },
    ],
    visual: "motion1d",
    caseTitle: "Jarak rem di jalan basah",
    casePlace: "Jalan kota",
    caseStory: "Mobil 20 m/s mengerem dengan perlambatan 4 m/s². Pengemudi ingin tahu berapa meter sebelum berhenti, bukan berapa detik.",
    caseMove: [
      "Arah gerak positif, jadi a = −4.",
      "v = 0, v0 = 20. Pakai v² = v0² + 2 a s.",
      "0 = 400 + 2(−4)s → s = 50 m. Butuh ruang, bukan hanya waktu reaksi.",
    ],
    caseTake: "Jika waktu tidak ada di pertanyaan, sering kali rumus tanpa t yang paling pendek.",
    traps: [
      { bad: "Memakai v = s/t padahal kecepatan berubah.", fix: "Itu hanya untuk kecepatan rata-rata konstan, atau definisi rata-rata." },
      { bad: "a positif saat mengerem ke arah positif.", fix: "Perlambatan berarti a berlawanan dengan kecepatan." },
    ],
    howTo: [
      "Tulis diketahui dan yang ditanya, termasuk yang nol.",
      "Coret rumus yang memuat besaran tak dikenal yang tidak ingin kamu buka.",
      "Mainkan visual: percepatan positif membuat jarak antar jejak makin jauh.",
    ],
    check: {
      q: "v0=0, a=2, t=3. Kecepatan akhir?",
      a: "6 m/s.",
      why: "v = 0 + 2×3.",
    },
    related: "parabola",
  },
  {
    id: "parabola",
    track: "physics",
    title: "Gerak parabola",
    blurb: "Horizontal jalan sendiri. Vertikal jatuh sendiri.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menebak di mana bola mendarat.",
    oneIdea: "Pecah gerak jadi dua: horizontal kecepatan tetap, vertikal seperti jatuh bebas. Waktu adalah jembatannya.",
    ideas: [
      { t: "Komponen", d: "vx = v cos θ tetap. vy berubah karena g." },
      { t: "Waktu dari vertikal", d: "Mendarat setinggi lempar: vy kembali kebalikannya." },
      { t: "Jarak dari waktu", d: "R = vx × t. Jangan memakai sin untuk jarak datar." },
    ],
    formulas: [
      { name: "Waktu di udara", tex: "t=\\dfrac{2 v_0 \\sin\\theta}{g}", when: "Mendarat setinggi titik lempar." },
      { name: "Tinggi maks", tex: "H=\\dfrac{v_0^2 \\sin^2\\theta}{2g}", when: "Puncak, vy = 0." },
      { name: "Jarak datar", tex: "R=\\dfrac{v_0^2 \\sin 2\\theta}{g}", when: "Tanah datar." },
    ],
    visual: "projectile",
    caseTitle: "Tendangan ke gawang",
    casePlace: "Lapangan",
    caseStory: "Bola ditendang 20 m/s pada 30°. Gawang berjarak 30 m, tanahnya datar, g = 10. Apakah jarak tempuhnya cukup?",
    caseMove: [
      "sin 60° ≈ 0,866 karena 2θ = 60°.",
      "R = 400 × 0,866 / 10 ≈ 34,6 m.",
      "34,6 > 30, jadi secara jarak datar bola mampu sampai, asal tidak terhalang pemain dan tinggi melewati mistar — itu dicek terpisah dengan H dan waktu.",
    ],
    caseTake: "Satu rumus menjawab satu pertanyaan. Jarak, waktu, dan tinggi tidak saling mengganti.",
    traps: [
      { bad: "Memakai g pada sumbu x.", fix: "Horizontal tidak ditarik g (abaikan udara)." },
      { bad: "sin 2θ dihitung sebagai sin θ dua kali.", fix: "2θ adalah sudutnya digandakan dulu." },
    ],
    howTo: [
      "Gambar dua sumbu. Tulis vx dan vy di ujung panah.",
      "Putuskan dulu: tanah datar atau tidak. Rumus R yang ringkas butuh tanah datar.",
      "Ubah sudut di lab sampai jarak paling jauh — di dekat 45°.",
    ],
    check: {
      q: "Komponen mana yang menentukan lama bola di udara pada tanah datar?",
      a: "Komponen vertikal.",
      why: "Waktu berasal dari gerak naik-turun. Horizontal hanya memakai waktu itu untuk menempuh jarak.",
    },
    related: "kinematika",
  },
  {
    id: "newton",
    track: "physics",
    title: "Gaya dan Newton",
    blurb: "Yang menggerakkan adalah gaya total, bukan gaya terbesar.",
    minutes: 12,
    level: "dasar",
    promise: "Kamu bisa menggambar gaya tanpa panah yang hilang.",
    oneIdea: "Percepatan sama dengan gaya total dibagi massa. Gaya yang saling mengalahkan, bukan yang sendiri paling besar, yang menentukan.",
    ideas: [
      { t: "Gambar dulu", d: "Setiap panah gaya yang menyentuh benda. Berat, normal, gesek, tarikan." },
      { t: "Berat bukan massa", d: "w = mg. Massa kilogram, berat newton." },
      { t: "Gesek", d: "Pada lantai datar, N = mg, gesek = μN, arah melawan kecenderungan gerak." },
    ],
    formulas: [
      { name: "Newton II", tex: "\\sum F = ma", when: "Massa tetap, dari kerangka inersial." },
      { name: "Berat", tex: "w=mg", when: "Dekat permukaan bumi, g tetap." },
      { name: "Gesek kinetik", tex: "f=\\mu N", when: "Sedang bergeser. N tidak selalu sama dengan berat." },
    ],
    visual: "forces",
    caseTitle: "Mendorong lemari",
    casePlace: "Kamar",
    caseStory: "Lemari 40 kg, μ = 0,4, g = 10. Berat 400 N, gesek maksimum kira-kira 160 N. Dorongan 100 N tidak mempercepat apa pun.",
    caseMove: [
      "N = 400 N pada lantai datar.",
      "Ambang gesek ≈ 0,4 × 400 = 160 N.",
      "Dorongan di bawah itu: gaya total nol, lemari tetap diam. Bukan karena 'massa menang', karena total gaya nol.",
    ],
    caseTake: "Diam itu juga jawaban fisika: ΣF = 0.",
    traps: [
      { bad: "a = F/m dengan F satu gaya, mengabaikan gesek.", fix: "Masukkan semua gaya pada sumbu yang sama." },
      { bad: "Normal selalu sama dengan berat.", fix: "Di bidang miring atau jika ada gaya vertikal lain, tidak." },
    ],
    howTo: [
      "Empat panah dulu, baru angka.",
      "Pilih sumbu +x searah gerak yang diharapkan.",
      "Geser gaya di visual sampai percepatan berbalik tanda, lalu jelaskan kenapa.",
    ],
    check: {
      q: "Massa 2 kg, gaya total 6 N. Percepatan?",
      a: "3 m/s².",
      why: "a = F/m.",
    },
    related: "energi",
  },
  {
    id: "energi",
    track: "physics",
    title: "Usaha dan energi",
    blurb: "Energi pindah bentuk. Ia tidak menghilang diam-diam.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa dapat kelajuan tanpa menghitung waktu.",
    oneIdea: "Usaha memindahkan energi. Pada gaya konservatif, jumlah kinetik dan potensial tetap.",
    ideas: [
      { t: "Usaha", d: "Gaya searah perpindahan. Gaya tegak lurus tidak usaha." },
      { t: "Kinetik", d: "Bergantung kelajuan kuadrat. Dua kali lebih cepat, empat kali energinya." },
      { t: "Potensial", d: "Butuh acuan. Sering tanah = 0." },
    ],
    formulas: [
      { name: "Usaha searah", tex: "W=Fs", when: "Gaya tetap dan sejajar perpindahan." },
      { name: "Kinetik", tex: "E_k=\\tfrac{1}{2}mv^2", when: "Semua gerak translasi sederhana." },
      { name: "Potensial gravitasi", tex: "E_p=mgh", when: "Dekat bumi, acuan ketinggian jelas." },
    ],
    visual: "energy",
    caseTitle: "Roller coaster tanpa mesin di lembah",
    casePlace: "Wahana",
    caseStory: "Kereta diam di puncak 5 m, lalu turun. Gesekan diabaikan dulu supaya kamu melihat batas ideal. g = 10.",
    caseMove: [
      "Di puncak, energi = m g × 5.",
      "Di dasar, itu menjadi ½ m v². Massa coret.",
      "v = √(2×10×5) = 10 m/s. Gesekan nyata membuatnya lebih pelan — energi itu jadi panas dan bunyi.",
    ],
    caseTake: "Energi tidak hilang. Ia sering hanya pindah ke bentuk yang tidak kamu inginkan.",
    traps: [
      { bad: "½ m v, lupa kuadrat.", fix: "Kelajuan dikuadratkan." },
      { bad: "Menjumlah tinggi tanpa acuan yang sama.", fix: "Pakai satu garis nol." },
    ],
    howTo: [
      "Tulis dua kolom: awal dan akhir. Isi EK dan EP masing-masing.",
      "Coret m jika ada di semua suku.",
      "Naikkan ketinggian di visual dan lihat batang energi bertukar, jumlahnya diam.",
    ],
    check: {
      q: "Kelajuan jadi 2 kali. Energi kinetik jadi berapa kali?",
      a: "4 kali.",
      why: "v². Dua kuadrat empat.",
    },
    related: "momentum",
  },
  {
    id: "momentum",
    track: "physics",
    title: "Momentum dan impuls",
    blurb: "Berapa banyak gerak, dan bagaimana tumbukan berbagi.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu paham kenapa airbag memperlama waktu.",
    oneIdea: "Momentum adalah massa kali kecepatan. Tanpa gaya luar, jumlah momentum sebelum dan sesudah sama.",
    ideas: [
      { t: "Arah", d: "Pilih positif. Yang berlawanan dapat tanda minus." },
      { t: "Menempel", d: "Massanya digabung, kecepatan jadi satu." },
      { t: "Impuls", d: "Gaya kali waktu = perubahan momentum. Waktu lebih lama, gaya lebih kecil untuk Δp yang sama." },
    ],
    formulas: [
      { name: "Momentum", tex: "p=mv", when: "Satu benda, satu arah." },
      { name: "Kekekalan", tex: "\\sum p_{\\text{awal}}=\\sum p_{\\text{akhir}}", when: "Gaya luar total diabaikan pada sumbu itu." },
      { name: "Impuls", tex: "J=F\\Delta t=\\Delta p", when: "Gaya rata-rata selama selang singkat." },
    ],
    visual: "collision",
    caseTitle: "Airbag dan waktu",
    casePlace: "Dashboard mobil",
    caseStory: "Kepala harus kehilangan momentum yang sama, entah menabrak setir atau mendarat di airbag. Δp sama. Airbag memperlama Δt.",
    caseMove: [
      "J = Δp tetap, misalnya dari 12 kg·m/s ke 0.",
      "Jika Δt = 0,01 s, gaya rata-rata 1200 N.",
      "Jika airbag membuat Δt = 0,1 s, gaya rata-rata 120 N. Sepuluh kali lebih lembut.",
    ],
    caseTake: "Memperlama berhenti menurunkan gaya. Itulah bantalan, tekukan lutut saat mendarat, dan zona remuk mobil.",
    traps: [
      { bad: "Menjumlah kelajuan, bukan momentum.", fix: "Kali massa dulu." },
      { bad: "Memakai kekekalan energi pada tumbukan menempel.", fix: "Menempel biasanya tidak lenting sempurna. Momentum tetap jalan, energi kinetik berkurang." },
    ],
    howTo: [
      "Gambar sebelum dan sesudah, dua kotak.",
      "Beri tanda plus minus sebelum menghitung.",
      "Tonton visual tumbukan: kecepatan bersama berada di antara dua kecepatan awal.",
    ],
    check: {
      q: "Massa 2 kg kecepatan 3 m/s. Momentum?",
      a: "6 kg·m/s.",
      why: "p = mv.",
    },
    related: "newton",
  },
  {
    id: "gelombang",
    track: "physics",
    title: "Getaran dan gelombang",
    blurb: "Pola jalan. Bahannya tetap di tempat.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa menghubungkan nada, tali, dan bandul.",
    oneIdea: "Gelombang memindahkan energi dan pola, bukan memindahkan mediumnya ke ujung.",
    ideas: [
      { t: "Tiga besaran", d: "Cepat rambat, frekuensi, panjang gelombang. Tahu dua, dapat yang ketiga." },
      { t: "Bandul kecil", d: "Periodenya bergantung panjang dan g, bukan massa dan bukan simpangan kecil." },
      { t: "Dawai", d: "Makin tegang, makin cepat. Makin berat per meter, makin lambat." },
    ],
    formulas: [
      { name: "Gelombang", tex: "v=f\\lambda", when: "Gelombang periodik." },
      { name: "Bandul", tex: "T=2\\pi\\sqrt{L/g}", when: "Simpangan kecil." },
      { name: "Dawai", tex: "v=\\sqrt{T/\\mu}", when: "T tegangan, μ massa per panjang." },
    ],
    visual: "wave",
    caseTitle: "Stem nada gitar",
    casePlace: "Senar",
    caseStory: "Senar yang sama, dipetik lebih kencang tegangannya, nadanya naik. Bukan karena senarnya memendek, tetapi karena gelombangnya lebih cepat sehingga frekuensi nada dasar naik.",
    caseMove: [
      "v = √(T/μ). T naik, v naik.",
      "Panjang gelombang nada dasar tetap 2L jika panjang senar tetap.",
      "f = v/λ naik. Itulah memutar tuner.",
    ],
    caseTake: "Frekuensi yang kamu dengar = cepat rambat dibagi panjang gelombang yang muat di senar.",
    traps: [
      { bad: "Periode bandul bergantung massa.", fix: "Massa tidak masuk rumus bandul sederhana." },
      { bad: "T pada dawai diartikan periode.", fix: "Di rumus dawai, T tegangan." },
    ],
    howTo: [
      "Gambar satu panjang gelombang dan tandai λ sebelum menghitung.",
      "Ubah amplitudo di lab: cepat rambat tidak ikut berubah. Amplitudo adalah tinggi, bukan kecepatan.",
      "Untuk bandul, coba di Studio. Pendekkan tali, ayunan makin cepat.",
    ],
    check: {
      q: "f = 10 Hz, λ = 2 m. Cepat rambat?",
      a: "20 m/s.",
      why: "v = fλ.",
    },
    related: "pde",
  },
  {
    id: "fluida",
    track: "physics",
    title: "Fluida",
    blurb: "Tekanan, gaya apung, dan pipa yang menyempit.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu paham kenapa bendungan tebal di bawah.",
    oneIdea: "Makin dalam, tekanan makin besar. Benda terdesak mendapat gaya ke atas sebesar berat fluida yang dipindahkan.",
    ideas: [
      { t: "Tekanan gauge", d: "Tambahan karena kedalaman: ρgh. Tekanan udara bisa ditambah terpisah." },
      { t: "Archimedes", d: "V yang dipakai adalah volume terdesak, belum tentu seluruh volume benda." },
      { t: "Kontinuitas", d: "Air tidak menumpuk. Pipa sempit membuat aliran lebih cepat." },
    ],
    formulas: [
      { name: "Kedalaman", tex: "P=P_0+\\rho g h", when: "Cairan diam." },
      { name: "Apung", tex: "F_A=\\rho_{f} g V_{\\text{desak}}", when: "Fluida yang didesak, bukan bahan benda." },
      { name: "Debit", tex: "A_1 v_1=A_2 v_2", when: "Aliran tunak, tak termampatkan." },
    ],
    visual: "fluid",
    caseTitle: "Kapal tidak harus dari kayu",
    casePlace: "Pelabuhan",
    caseStory: "Lambung baja tenggelam jika berupa balok pejal, tetapi terapung jika berbentuk mangkuk. Yang berubah bukan 'jenis ajaib', melainkan volume air yang didesak.",
    caseMove: [
      "Berat kapal = gaya apung saat mengapung seimbang.",
      "F_A = ρ_air g V_desak.",
      "Baja padat mendesak sedikit dibanding massanya. Lambung berongga mendesak banyak air sebelum tenggelam.",
    ],
    caseTake: "Terapung adalah perbandingan berat dengan kemampuan mendesak fluida, bukan mitos bahan.",
    traps: [
      { bad: "ρ dalam Archimedes adalah rapat benda.", fix: "Rapat fluidanya." },
      { bad: "Pipa sempit, tekanan selalu lebih besar.", fix: "Kecepatan naik. Tekanan pada aliran ideal sering turun. Jangan dicampur dengan tekanan kedalaman." },
    ],
    howTo: [
      "Gambar permukaan air dan sebuah titik. h diukur ke atas dari titik itu.",
      "Tulis ρ mana: benda atau fluida.",
      "Geser kedalaman di visual. Tekanan harus naik linear, bukan kuadrat.",
    ],
    check: {
      q: "Pipa menyempit, debit tetap. Kecepatan air?",
      a: "Naik.",
      why: "A v konstan. A kecil, v besar.",
    },
    related: "newton",
  },
  {
    id: "listrik",
    track: "physics",
    title: "Listrik",
    blurb: "Dorongan, hambatan, dan gaya antar muatan.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa membaca rangkaian sederhana sebelum menyalakannya.",
    oneIdea: "Tegangan mendorong, hambatan menahan, arus adalah muatan yang lewat tiap detik.",
    ideas: [
      { t: "Ohm", d: "V = IR untuk resistor ohmik. Naikkan V, arus naik, jika R tetap." },
      { t: "Seri dan paralel", d: "Seri: hambatan bertambah. Paralel: ada jalan lain, hambatan pengganti turun." },
      { t: "Coulomb", d: "Gaya antar muatan titik mengikuti 1/r². Muatan sejenis tolak." },
    ],
    formulas: [
      { name: "Ohm", tex: "V=IR", when: "Resistor." },
      { name: "Seri / paralel dua R", tex: "R_s=R_1+R_2,\\quad R_p=\\dfrac{R_1 R_2}{R_1+R_2}", when: "Dua hambatan." },
      { name: "Coulomb", tex: "F=k\\dfrac{|q_1 q_2|}{r^2}", when: "Muatan titik, k = 9×10⁹." },
    ],
    visual: "circuit",
    caseTitle: "Stopkontak dan kabel ekstensi",
    casePlace: "Kamar kos",
    caseStory: "Satu jalur stopkontak 220 V. Menyambung banyak alat paralel seperti menambah jalan bagi arus. Arus total naik. Kabel yang terlalu kecil memanas.",
    caseMove: [
      "Tiap alat menarik I = P/V. Contoh 440 W pada 220 V menarik 2 A.",
      "Tiga alat serupa paralel menarik kira-kira 6 A.",
      "Sekering 5 A putus untuk melindungi kabel. Itu bukan alatnya 'rusak', itu batas arus.",
    ],
    caseTake: "Paralel memudahkan arus. Kemudahan itu harus diimbangi kabel dan sekering.",
    traps: [
      { bad: "Hambatan paralel dijumlahkan.", fix: "Yang dijumlah kebalikan hambatannya, atau pakai rumus perkalian-per-jumlah untuk dua R." },
      { bad: "Lupa μC = 10⁻⁶ saat Coulomb.", fix: "Ubah ke coulomb sebelum kali k." },
    ],
    howTo: [
      "Gambar rangkaian, tandai satu arus pada seri.",
      "Untuk paralel, tegangan cabang sama.",
      "Di visual muatan (Studio), jauhkan dua muatan: panah medan melemah cepat.",
    ],
    check: {
      q: "R = 4 Ω, I = 2 A. V?",
      a: "8 V.",
      why: "V = IR.",
    },
    related: "optik",
  },
  {
    id: "optik",
    track: "physics",
    title: "Cahaya dan lensa",
    blurb: "Sinar lurus sampai ada yang membelokkannya.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa menempatkan bayangan lensa tipis.",
    oneIdea: "Lensa tipis mengumpulkan atau menyebarkan sinar karena tiap bagian membelokkan sedikit. Jarak benda, bayangan, dan fokus terikat satu rumus.",
    ideas: [
      { t: "Fokus", d: "Sinar sejajar sumbu dikumpulkan di titik fokus, untuk lensa cembung tipis ideal." },
      { t: "Rumus lensa", d: "Kebalikan jarak dijumlah. Satuan ketiga jarak harus sama." },
      { t: "Snell", d: "n sin sudut tetap saat melewati batas. Sudut diukur dari garis normal, bukan dari permukaan." },
    ],
    formulas: [
      { name: "Lensa tipis", tex: "\\dfrac{1}{f}=\\dfrac{1}{s}+\\dfrac{1}{s'}", when: "Lensa tipis, sinar paraksial." },
      { name: "Perbesaran", tex: "m=-\\dfrac{s'}{s}", when: "Tanda minus: bayangan terbalik." },
      { name: "Snell", tex: "n_1\\sin i = n_2\\sin r", when: "Dua medium." },
    ],
    visual: "lens",
    caseTitle: "Kacamata untuk rabun dekat",
    casePlace: "Meja baca",
    caseStory: "Mata yang sulit fokus pada buku membutuhkan lensa yang menggeser letak bayangan supaya jatuh di retina. Angka minus/plus pada resep terkait daya lensa, yaitu 1/f.",
    caseMove: [
      "Daya dalam dioptri = 1/f jika f dalam meter.",
      "Lensa +2 D punya f = 0,5 m.",
      "Rumus lensa lalu memakai f itu bersama jarak benda untuk menemukan jarak bayangan.",
    ],
    caseTake: "Resep kacamata adalah fokus yang dibalik, dinyatakan supaya angkanya nyaman.",
    traps: [
      { bad: "Mencampur cm dan m dalam 1/f.", fix: "Satu satuan untuk f, s, dan s'." },
      { bad: "Sudut Snell dari permukaan kaca.", fix: "Dari garis normal." },
    ],
    howTo: [
      "Gambar lensa, tanda F di dua sisi, baru benda.",
      "Hitung 1/s' sebagai selisih dua pecahan, baru dibalik.",
      "Geser benda di visual: makin jauh, bayangan mendekati fokus.",
    ],
    check: {
      q: "f=10 cm, s=20 cm. s'?",
      a: "20 cm.",
      why: "1/10 = 1/20 + 1/s' sehingga s' = 20.",
    },
    related: "gelombang",
  },
  {
    id: "foton",
    track: "physics",
    title: "Foton",
    blurb: "Cahaya datang dalam paket energi.",
    minutes: 10,
    level: "menengah",
    promise: "Kamu bisa menghubungkan warna dengan energi elektron.",
    oneIdea: "Satu foton membawa energi yang ditentukan frekuensinya. Elektron lepas hanya jika paket itu cukup besar, bukan jika lampunya sekadar lebih terang.",
    ideas: [
      { t: "Warna dan energi", d: "Gelombang lebih pendek, energi foton lebih besar. Ungu lebih besar daripada merah." },
      { t: "Fungsi kerja", d: "Ongkos minimum agar elektron lepas dari logam." },
      { t: "Terang", d: "Menambah terang menambah jumlah foton, bukan energi tiap foton." },
    ],
    formulas: [
      { name: "Perkiraan handy", tex: "E(\\mathrm{eV})\\approx \\dfrac{1240}{\\lambda(\\mathrm{nm})}", when: "Menghitung cepat." },
      { name: "Efek fotolistrik", tex: "K_{\\max}=E-\\phi", when: "Hanya jika E > φ, selain itu nol." },
      { name: "Frekuensi ambang", tex: "\\phi = h f_0", when: "Di bawah f0 tidak ada elektron, seberapa pun terangnya." },
    ],
    visual: "photon",
    caseTitle: "Sensor pintu dan lampu merah",
    casePlace: "Lift",
    caseStory: "Sebuah logam tidak memancarkan elektron saat disinari lampu merah yang sangat terang, tetapi memancarkan saat disinari ungu yang redup.",
    caseMove: [
      "Hitung E merah, misalnya 700 nm → sekitar 1,8 eV.",
      "Jika φ logam 2,2 eV, merah tidak cukup. K = 0.",
      "Ungu 400 nm → sekitar 3,1 eV. K maks ≈ 0,9 eV. Terang hanya menambah jumlah elektron, bukan K maks.",
    ],
    caseTake: "Ambang ditentukan energi per foton, yaitu warna, bukan kecerahan.",
    traps: [
      { bad: "Lampu lebih terang selalu membuat elektron lebih cepat.", fix: "Terang menambah jumlah. Warna menambah energi tiap foton." },
      { bad: "K = φ − E.", fix: "Energi foton dikurangi ongkos, bukan sebaliknya." },
    ],
    howTo: [
      "Selalu cek E > φ sebelum menghitung K.",
      "Pakai 1240/λ supaya tidak tersesat di pangkat 10.",
      "Geser panjang gelombang di visual sampai melewati ambang.",
    ],
    check: {
      q: "E = 2 eV, φ = 3 eV. K maks?",
      a: "0.",
      why: "Paket energi tidak cukup. Elektron tidak lepas.",
    },
    related: "listrik",
  },
  {
    id: "kompleks",
    track: "advanced",
    title: "Bilangan kompleks",
    blurb: "Pasangan bilangan yang bisa diputar. Riley bab 3.",
    chapter: "Riley, Hobson & Bence — bab 3",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu melihat i sebagai putaran, bukan sebagai siluman.",
    oneIdea: "Bilangan kompleks adalah titik di bidang. Mengalikan dengan i memutar 90°. Modulus adalah jarak ke asal.",
    ideas: [
      { t: "Bentuk", d: "z = x + iy. x yang biasa, y yang di arah i." },
      { t: "Kalikan", d: "Modulus dikali, argumen dijumlah. i² = −1 memunculkan tanda minus di bagian real." },
      { t: "Euler", d: "e^{iθ} = cos θ + i sin θ. Inilah jembatan ke gelombang dan arus bolak-balik." },
    ],
    formulas: [
      { name: "Modulus", tex: "|z|=\\sqrt{x^2+y^2}", when: "Jarak di bidang Argand." },
      { name: "Perkalian", tex: "(a+bi)(c+di)=(ac-bd)+(ad+bc)i", when: "Membuka kurung dengan i²=−1." },
      { name: "Euler", tex: "e^{i\\theta}=\\cos\\theta+i\\sin\\theta", when: "Fase pada osilasi." },
    ],
    visual: "argand",
    caseTitle: "Impedansi speaker",
    casePlace: "Rangkaian AC",
    caseStory: "Resistor menahan searah dengan arus. Kumparan menahan dengan pergeseran fase. Keduanya digabung jadi satu bilangan kompleks Z = R + iX, bukan dua hambatan yang asal dijumlah.",
    caseMove: [
      "R = 3 Ω, X = 4 Ω.",
      "|Z| = 5 Ω. Arus efektif memakai modulus ini bersama tegangan.",
      "Argumen Z memberitahu seberapa jauh tegangan mendahului arus.",
    ],
    caseTake: "Bilangan kompleks di teknik menyimpan besar dan fase dalam satu simbol.",
    traps: [
      { bad: "Menganggap i sama dengan −1.", fix: "i² yang sama dengan −1." },
      { bad: "Modulus = x + y.", fix: "Itu jumlah, bukan jarak. Pakai Pythagoras." },
    ],
    howTo: [
      "Gambar sumbu real dan imajiner setiap soal.",
      "Ucapkan: kali i = putar 90° berlawanan jarum jam.",
      "Setelah rumus, tutup buku dan hitung |3+4i| dari ingatan.",
    ],
    check: {
      q: "|3+4i|?",
      a: "5.",
      why: "Segitiga 3-4-5.",
    },
    related: "residu",
  },
  {
    id: "deret",
    track: "advanced",
    title: "Deret dan hampiran",
    blurb: "Jumlah panjang, dan suku yang cukup. Riley bab 4.",
    chapter: "Riley, Hobson & Bence — bab 4",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu tahu kapan boleh memotong ekor deret.",
    oneIdea: "Deret adalah jumlah yang panjang. Sering cukup beberapa suku pertama, asal kamu tahu sisanya mengecil.",
    ideas: [
      { t: "Geometri", d: "Pengali tetap. Ada rumus jumlah tertutup." },
      { t: "Syarat tak hingga", d: "|r| < 1 atau jumlahnya lari." },
      { t: "Taylor", d: "Fungsi mulus dihampiri polinom. e^x mulai dari 1 + x + x²/2." },
    ],
    formulas: [
      { name: "Geometri hingga", tex: "S=a\\dfrac{r^n-1}{r-1}", when: "r ≠ 1." },
      { name: "Tak hingga", tex: "S=\\dfrac{a}{1-r}", when: "|r|<1." },
      { name: "Awal eksponensial", tex: "e^x \\approx 1+x+\\dfrac{x^2}{2}", when: "x kecil, atau sebagai latihan suku." },
    ],
    visual: "series",
    caseTitle: "Kalkulator yang tidak menyimpan e",
    casePlace: "Mesin hitung lama, dan mesin sekarang",
    caseStory: "Tombol e^x tidak memanggil nilai ajaib. Ia menjumlahkan suku sampai suku baru lebih kecil daripada ketelitian layar.",
    caseMove: [
      "Untuk x = 1: 1 + 1 + 1/2 = 2,5.",
      "Suku berikutnya 1/6 ≈ 0,167, jumlah ≈ 2,667.",
      "e sebenarnya ≈ 2,718. Ekornya makin kecil. Itulah deret yang berguna.",
    ],
    caseTake: "Hampiran tanpa taksiran sisa hanya tebakan. Di latihan ini kamu menghitung suku yang diminta, bukan berpura-pura itu nilai akhir.",
    traps: [
      { bad: "Memakai rumus tak hingga untuk r = 2.", fix: "Jumlahnya meledak." },
      { bad: "Berhenti di suku pertama lalu menyebutnya jawaban eksak.", fix: "Sebut saja hampiran n suku." },
    ],
    howTo: [
      "Tulis 4 suku terpisah sebelum menjumlah.",
      "Cek |r| sebelum rumus tak hingga.",
      "Di visual, tambah suku sampai batang tambahan hampir tidak terlihat.",
    ],
    check: {
      q: "Jumlah tak hingga 8 + 4 + 2 + 1 + …?",
      a: "16.",
      why: "a=8, r=1/2, S = 8/(1/2) = 16.",
    },
    related: "eksponen",
  },
  {
    id: "parsial",
    track: "advanced",
    title: "Turunan parsial",
    blurb: "Bekukan satu variabel. Riley bab 5.",
    chapter: "Riley, Hobson & Bence — bab 5",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa membaca kemiringan sebuah bukit pada peta.",
    oneIdea: "Turunan parsial mengubah satu variabel dan membekukan yang lain. Itu kemiringan permukaan di satu arah.",
    ideas: [
      { t: "Yang dibekukan adalah konstanta", d: "y tetap saat ∂/∂x, sekalipun y nanti diganti angka." },
      { t: "Gradien", d: "Vektor semua turunan parsial. Arahnya paling curam naik." },
      { t: "Hampiran", d: "Perubahan kecil ≈ fx dx + fy dy." },
    ],
    formulas: [
      { name: "Parsial", tex: "\\partial_x (x^2 y)=2xy", when: "y konstanta." },
      { name: "Gradien", tex: "\\nabla f=(\\partial_x f,\\partial_y f,\\partial_z f)", when: "Arah tercepat naik." },
      { name: "Diferensial", tex: "df \\approx f_x dx + f_y dy", when: "Langkah kecil di sekitar titik." },
    ],
    visual: "surface",
    caseTitle: "Pendaki dan peta kontur",
    casePlace: "Bukit",
    caseStory: "Peta kontur rapat berarti curam. Pendaki yang ingin paling cepat naik tidak berjalan sepanjang kontur. Ia memotong tegak lurus kontur — arah gradien.",
    caseMove: [
      "Pilih titik. Hitung ∂f/∂x dan ∂f/∂y.",
      "Vektor (fx, fy) adalah arah langkah paling curam.",
      "Berjalan sepanjang kontur, f tidak berubah, jadi langkah itu tegak lurus gradien.",
    ],
    caseTake: "Dua turunan parsial bersama-sama lebih berguna daripada masing-masing sendirian.",
    traps: [
      { bad: "Menurunkan semua variabel sekaligus.", fix: "Satu simbol ∂, satu variabel." },
      { bad: "Menganggap y² hilang saat turunan ke x selalu.", fix: "Jika y² dikali fungsi x, ia tetap sebagai koefisien." },
    ],
    howTo: [
      "Lingkari variabel yang bergerak. Yang lain tulis sebagai angka di pinggir.",
      "Setelah turunan, baru masukkan titik.",
      "Miringkan permukaan di lab. Bagian yang paling berdiri adalah arah gradien besar.",
    ],
    check: {
      q: "f=x²y. ∂f/∂y sama dengan?",
      a: "x².",
      why: "y turun jadi 1, x dibekukan.",
    },
    related: "medan",
  },
  {
    id: "lipat",
    track: "advanced",
    title: "Integral lipat",
    blurb: "Menjumlah di sebuah daerah, bukan di garis. Riley bab 6.",
    chapter: "Riley, Hobson & Bence — bab 6",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa menghitung massa benda yang tidak seragam.",
    oneIdea: "Integral lipat menjumlahkan nilai di seluruh daerah. Kerjakan integral paling dalam dulu, sambil menganggap variabel luar tetap.",
    ideas: [
      { t: "Dalam lalu luar", d: "Seperti mengiris daerah jadi strip, menjumlah strip, lalu menjumlah strip-strip itu." },
      { t: "Konstanta", d: "Integral konstanta di persegi panjang = konstanta × luas." },
      { t: "Rapat", d: "Massa = ∫∫ ρ dA. Jika ρ berubah, ia tidak boleh dikeluarkan." },
    ],
    formulas: [
      { name: "Persegi", tex: "\\int_0^A\\int_0^B f(x,y)\\,dy\\,dx", when: "Batas konstan, urutan boleh ditukar jika f ramah." },
      { name: "Massa", tex: "M=\\iint_R \\rho\\,dA", when: "Rapat per luas." },
      { name: "Luas", tex: "A=\\iint_R 1\\,dA", when: "Fungsi 1." },
    ],
    visual: "surface",
    caseTitle: "Pelat logam yang tidak sejenis",
    casePlace: "Bengkel",
    caseStory: "Sebuah pelat persegi ditebalkan di satu sisi sehingga rapat massa bergantung pada x. Menimbang secara teori berarti menjumlah ρ di setiap titik, bukan mengalikan rata-rata kira-kira.",
    caseMove: [
      "Tulis batas x dan y.",
      "Integralkan y lebih dulu jika ρ hanya bergantung x: hasilnya ρ(x) kali lebar y.",
      "Baru integralkan terhadap x. Itu massa.",
    ],
    caseTake: "Rata-rata yang adil untuk rapat tidak seragam adalah integral, bukan tebakan di tengah.",
    traps: [
      { bad: "Mengintegralkan dua variabel dalam satu langkah campur.", fix: "Satu integral, satu d-sesuatu." },
      { bad: "Lupa bahwa batas dalam boleh mengandung variabel luar.", fix: "Di persegi panjang batasnya konstan. Di segitiga sering tidak." },
    ],
    howTo: [
      "Gambar daerah dan arsir strip yang kamu jumlahkan dulu.",
      "Tulis batas di bawah tanda integral, jangan di kepala.",
      "Cek dimensi: massa harus positif untuk ρ positif.",
    ],
    check: {
      q: "∫_0^1 ∫_0^1 4 dy dx?",
      a: "4.",
      why: "Luas persegi 1, kali 4.",
    },
    related: "integral",
  },
  {
    id: "matriks",
    track: "advanced",
    title: "Matriks dan silang",
    blurb: "Mesin linear dan luas berarah. Riley bab 7–8.",
    chapter: "Riley, Hobson & Bence — bab 7 dan 8",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa membaca matriks sebagai pemutar dan peregang.",
    oneIdea: "Matriks 2×2 meregangkan bidang. Determinan adalah faktor luas, lengkap dengan tanda orientasi. Perkalian silang di 3D menghasilkan vektor tegak lurus.",
    ideas: [
      { t: "Urutan", d: "AB tidak selalu sama dengan BA." },
      { t: "Determinan 2×2", d: "ad − bc. Nol berarti luas hancur, informasi hilang." },
      { t: "Silang", d: "a×b tegak lurus a dan b. Besarnya luas jajar genjang." },
    ],
    formulas: [
      { name: "Determinan", tex: "\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=ad-bc", when: "Orientasi dan luas." },
      { name: "Komponen z silang", tex: "(a\\times b)_z=a_x b_y-a_y b_x", when: "Hanya butuh komponen xy." },
      { name: "Momen gaya", tex: "\\boldsymbol\\tau=\\mathbf r\\times\\mathbf F", when: "Kunci inggris, engsel, orbit." },
    ],
    visual: "vector",
    caseTitle: "Kunci yang selip",
    casePlace: "Ban mobil",
    caseStory: "Mendorong kunci dekat mur hampir tidak memutar. Mendorong di ujung gagang, tegak lurus gagang, memutar kuat. Yang masuk bukan besar gaya saja, melainkan r × F.",
    caseMove: [
      "r dari mur ke tangan, F arah dorongan.",
      "Jika F sejajar r, silang nol: tidak ada putaran.",
      "Jika tegak lurus, |τ| = r F. Gagang dua kali lebih panjang, momen dua kali, gaya yang sama.",
    ],
    caseTake: "Silang mengukur seberapa tegak lurus dua arah, sekaligus seberapa besar.",
    traps: [
      { bad: "ad + bc.", fix: "Determinan mengurangi." },
      { bad: "a×b = b×a.", fix: "Tanda terbalik." },
    ],
    howTo: [
      "Untuk det, tandai dua diagonal dengan dua warna.",
      "Untuk silang, tulis komponen dalam kolom supaya tidak tertukar.",
      "Putar panah di lab dan lihat resultan. Silang akan kamu hitung di kertas, penjumlahannya di gambar.",
    ],
    check: {
      q: "det [[1,0],[0,1]]?",
      a: "1.",
      why: "Identitas tidak mengubah luas.",
    },
    related: "vektor",
  },
  {
    id: "medan",
    track: "advanced",
    title: "Grad, div, curl",
    blurb: "Naik, menyebar, berputar. Riley bab 10.",
    chapter: "Riley, Hobson & Bence — bab 10",
    minutes: 14,
    level: "lanjut",
    promise: "Tiga kata ini cukup untuk membaca sebuah medan.",
    oneIdea: "Gradien naik, divergensi menyebar, curl berputar.",
    ideas: [
      { t: "Grad pada skalar", d: "Masukan angka, keluaran vektor." },
      { t: "Div pada vektor", d: "Masukan vektor, keluaran angka. Positif seperti sumber." },
      { t: "Curl pada vektor", d: "Masukan vektor, keluaran vektor. Mengukur pusaran lokal." },
    ],
    formulas: [
      { name: "Div", tex: "\\nabla\\cdot\\mathbf F=\\partial_x F_x+\\partial_y F_y+\\partial_z F_z", when: "Sumber atau sumur." },
      { name: "Curl z", tex: "(\\nabla\\times\\mathbf F)_z=\\partial_x F_y-\\partial_y F_x", when: "Pusaran di bidang xy." },
      { name: "Grad", tex: "\\nabla f=(\\partial_x f,\\partial_y f,\\partial_z f)", when: "Medan dari potensial." },
    ],
    visual: "field",
    caseTitle: "AC dan pusaran debu",
    casePlace: "Ruangan",
    caseStory: "Di depan kisi AC, udara seolah lahir — divergensi positif kalau kamu hanya melihat ruangan tanpa saluran. Di sudut ruangan, debu berputar: curl tidak nol, walau tidak ada sumber baru.",
    caseMove: [
      "Medan F = (x, y, 0) menyebar. Div = 2.",
      "Medan F = (−y, x, 0) berputar. Div = 0, curl z = 2.",
      "Kamu bisa punya pusaran tanpa sumber, dan sumber tanpa pusaran.",
    ],
    caseTake: "Div dan curl menjawab dua pertanyaan yang berbeda. Jangan ditukar.",
    traps: [
      { bad: "Div dari skalar.", fix: "Div butuh vektor." },
      { bad: "Curl z = ∂Fx/∂x − ∂Fy/∂y.", fix: "Itu campur dengan divergensi. Curl z memakai ∂Fy/∂x − ∂Fx/∂y." },
    ],
    howTo: [
      "Tulis tiga komponen F dalam satu baris sebelum menurunkan.",
      "Ubah mode di lab: sumber vs pusaran. Sebut satu kata.",
      "Satu soal, satu operator. Jangan hitung ketiganya kalau soal hanya minta satu.",
    ],
    check: {
      q: "Div dari F=(x, y, z)?",
      a: "3.",
      why: "1+1+1.",
    },
    related: "fluks",
  },
  {
    id: "fluks",
    track: "advanced",
    title: "Fluks dan Gauss",
    blurb: "Berapa banyak medan yang menusuk. Riley bab 11.",
    chapter: "Riley, Hobson & Bence — bab 11",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu tidak perlu menghitung enam muka jika divergensinya konstan.",
    oneIdea: "Fluks mengukur seberapa banyak medan menusuk sebuah permukaan. Pada permukaan tertutup, ia sama dengan isi divergensi di dalam.",
    ideas: [
      { t: "Menusuk", d: "Medan yang hanya menyentuh sejajar permukaan tidak menyumbang fluks." },
      { t: "Gauss", d: "Fluks keluar = integral volume dari divergensi." },
      { t: "Kubus simetris", d: "Jika div konstan, kali saja dengan volume." },
    ],
    formulas: [
      { name: "Fluks", tex: "\\Phi=\\iint \\mathbf F\\cdot d\\mathbf A", when: "Permukaan berarah." },
      { name: "Gauss", tex: "\\oint \\mathbf F\\cdot d\\mathbf A=\\iiint \\nabla\\cdot\\mathbf F\\,dV", when: "Permukaan tertutup, orientasi keluar." },
      { name: "Div konstan", tex: "\\Phi=(\\nabla\\cdot\\mathbf F)\\, V", when: "Contoh kubus dan F linear." },
    ],
    visual: "field",
    caseTitle: "Mengapa hukum Gauss menyukai simetri",
    casePlace: "Kabel koaksial",
    caseStory: "Medan listrik di sekitar kawat panjang seragam arahnya. Menghitung medan titik demi titik berat. Silinder khayal membuat fluks mudah: hanya selimut yang tembus, dan fluks itu sama dengan muatan di dalam dibagi ε0.",
    caseMove: [
      "Pilih permukaan yang medan menembusnya tegak lurus dan besarnya tetap.",
      "Fluks = E kali luas selimut.",
      "Sisi kanan = muatan tertutup / ε0. Lalu selesaikan E.",
    ],
    caseTake: "Teorema mengizinkan kamu mengganti permukaan rumit dengan isi di dalamnya, jika simetrinya membantu.",
    traps: [
      { bad: "Memakai Gauss pada permukaan terbuka.", fix: "Permukaannya harus tertutup, atau tutup sendiri secara sadar." },
      { bad: "Lupa orientasi keluar.", fix: "Fluks keluar positif untuk sumber." },
    ],
    howTo: [
      "Gambar permukaan tertutup, tanda panah keluar.",
      "Hitung div dulu. Jika konstan, selesai dengan kali volume.",
      "Lihat medan sumber di lab: panah keluar, itu fluks positif.",
    ],
    check: {
      q: "F=(x,y,z), kubus sisi 1. Fluks keluar?",
      a: "3.",
      why: "Div 3, volume 1.",
    },
    related: "medan",
  },
  {
    id: "fourier",
    track: "advanced",
    title: "Deret Fourier",
    blurb: "Sinyal rumit sebagai jumlah sinus. Riley bab 12.",
    chapter: "Riley, Hobson & Bence — bab 12",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa mendengar sebuah grafik.",
    oneIdea: "Banyak sinyal berulang adalah jumlah gelombang sinus yang frekuensinya kelipatan. Koefisien memberitahu seberapa keras tiap kelipatan.",
    ideas: [
      { t: "Fungsi ganjil", d: "f(−x) = −f(x) sering hanya butuh sinus, kosinusnya nol." },
      { t: "bn untuk f(x)=x", d: "Pada (−π, π), bn = 2 (−1)^{n+1} / n." },
      { t: "Makin tinggi n", d: "Suku mengecil, tetapi sudut gelombang makin tajam. Itulah detail sinyal." },
    ],
    formulas: [
      { name: "Bentuk", tex: "f(x)=\\tfrac{a_0}{2}+\\sum (a_n\\cos nx+b_n\\sin nx)", when: "Periode 2π." },
      { name: "Sinus", tex: "b_n=\\dfrac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\sin nx\\,dx", when: "Koefisien." },
      { name: "Kasus x", tex: "b_n=\\dfrac{2(-1)^{n+1}}{n}", when: "f(x)=x di (−π, π)." },
    ],
    visual: "fourier",
    caseTitle: "Equalizer lagu",
    casePlace: "Pemutar musik",
    caseStory: "Batang equalizer bukan hiasan. Tiap batang adalah seberapa besar sekelompok frekuensi dalam sinyal. Menaikkan bass berarti memperbesar koefisien frekuensi rendah.",
    caseMove: [
      "Satu nada murni hampir satu batang.",
      "Denting tajam butuh banyak kelipatan — suku n tinggi.",
      "Pada deret f(x)=x, b1=2, b2=−1, b3=2/3. Kelipatan tinggi mengecil tetapi tidak nol.",
    ],
    caseTake: "Detail tajam butuh frekuensi tinggi. Itulah sebabnya memotong frekuensi membuat sinyal tumpul.",
    traps: [
      { bad: "a0 dihitung seperti an biasa tanpa faktor.", fix: "Perhatikan konvensi a0/2 di rumus. Di soal latihan ini yang ditanya bn." },
      { bad: "Tanda bn ditebak semua positif.", fix: " (−1)^{n+1} berganti." },
    ],
    howTo: [
      "Gambar fungsi pada −π sampai π sebelum rumus.",
      "Cek ganjil atau genap supaya separuh koefisien langsung nol.",
      "Naikkan jumlah sinus di visual sampai gigi gergaji mulai terlihat.",
    ],
    check: {
      q: "Untuk f(x)=x, b1 menurut rumus 2(−1)^{n+1}/n?",
      a: "2.",
      why: "n=1, tanda positif, 2/1.",
    },
    related: "deret",
  },
  {
    id: "laplace",
    track: "advanced",
    title: "Transformasi Laplace",
    blurb: "Persamaan diferensial menjadi aljabar. Riley bab 13.",
    chapter: "Riley, Hobson & Bence — bab 13",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu punya jalan pintas untuk rangkaian yang baru dinyalakan.",
    oneIdea: "Laplace mengubah turunan menjadi perkalian dengan s. Kamu menyelesaikan aljabar, lalu kembali jika perlu.",
    ideas: [
      { t: "Kamus kecil", d: "1 → 1/s, t → 1/s², e^{at} → 1/(s−a), sin ωt → ω/(s²+ω²)." },
      { t: "Syarat awal", d: "L{y'} = s Y − y(0). Kondisi awal tidak menempel di akhir, ia masuk di sini." },
      { t: "Nilai di satu s", d: "Latihan ini meminta angka pada s tertentu, supaya kamu memakai kamus, bukan tabel hafalan buta." },
    ],
    formulas: [
      { name: "Konstanta", tex: "\\mathcal L\\{1\\}=1/s", when: "s>0." },
      { name: "Eksponen", tex: "\\mathcal L\\{e^{at}\\}=1/(s-a)", when: "s>a." },
      { name: "Sinus", tex: "\\mathcal L\\{\\sin\\omega t\\}=\\omega/(s^2+\\omega^2)", when: "Osilasi." },
    ],
    visual: "laplace",
    caseTitle: "Saklar yang baru ditutup",
    casePlace: "Rangkaian RC",
    caseStory: "Sebelum saklar ditutup, kapasitor kosong. Sesudahnya tegangan naik seperti 1 − e^{−t/RC}. Laplace menyukai soal 'mendadak menyala' karena syarat awal explicit.",
    caseMove: [
      "Persamaan diferensial di t diubah jadi aljabar di s.",
      "Syarat V(0)=0 masuk lewat rumus turunan.",
      "Balikkan transformasi: muncul eksponen yang kamu lihat sebagai kurva pengisian.",
    ],
    caseTake: "Kalau kamu hanya butuh nilai transform di satu s, jangan balikkan. Hitung saja dari kamus.",
    traps: [
      { bad: "L{e^{at}} = 1/(s+a) untuk a positif.", fix: "Penyebut s − a." },
      { bad: "L{sin ωt} pembilangnya s.", fix: "Pembilang ω. Yang pembilangnya s adalah kosinus." },
    ],
    howTo: [
      "Tulis kamus 4 baris di kartu terpisah. Bawa sampai hafal.",
      "Lingkari syarat awal sebelum transform.",
      "Lihat kurva e^{−at}: itulah wajah waktu dari kutub di s = −a.",
    ],
    check: {
      q: "L{1} di s=2?",
      a: "1/2.",
      why: "1/s = 1/2.",
    },
    related: "ode",
  },
  {
    id: "ode",
    track: "advanced",
    title: "Persamaan diferensial biasa",
    blurb: "Hubungan besaran dengan lajunya. Riley bab 14–15.",
    chapter: "Riley, Hobson & Bence — bab 14 dan 15",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu mengenali peluruhan, pertumbuhan, dan ayunan dari bentuknya.",
    oneIdea: "Jawaban persamaan diferensial adalah fungsi. Syarat awal memilih satu fungsi dari keluarga yang tak hingga.",
    ideas: [
      { t: "y' = k y", d: "Solusi eksponen. k negatif meluruh, positif meledak." },
      { t: "Waktu paruh", d: "Selang sampai tinggal setengah. Tidak bergantung jumlah awal." },
      { t: "Osilator", d: "x'' + ω² x = 0. ω = √(k/m). Periode 2π/ω." },
    ],
    formulas: [
      { name: "Pertumbuhan", tex: "y=y_0 e^{kt}", when: "y'=ky." },
      { name: "Paruh", tex: "y=y_0 / 2^{t/T}", when: "T waktu paruh." },
      { name: "Harmonik", tex: "\\omega=\\sqrt{k/m},\\quad T=2\\pi/\\omega", when: "Tanpa redaman." },
    ],
    visual: "ode",
    caseTitle: "Obat di darah",
    casePlace: "Jadwal dosis",
    caseStory: "Setelah satu dosis, kadar obat sering turun dengan waktu paruh yang kira-kira tetap. Dokter tidak menunggu sampai nol — nol secara teori tidak pernah tiba pada peluruhan eksponen murni.",
    caseMove: [
      "Paruh 4 jam, awal 200 mg.",
      "Setelah 12 jam = 3 paruh.",
      "Sisa 200/8 = 25 mg. Dosis berikut dirancang di atas sisa ini, bukan di atas nol.",
    ],
    caseTake: "Eksponen tidak habis di waktu berhingga. Praktisnya kamu pilih ambang, misalnya 1%.",
    traps: [
      { bad: "Mengurangi sejumlah tetap tiap paruh.", fix: "Yang tetap adalah faktor setengah, bukan selisih." },
      { bad: "T = ω.", fix: "Periode adalah 2π/ω." },
    ],
    howTo: [
      "Sebelum rumus, klasifikasi: meluruh, tumbuh, atau berayun.",
      "Syarat awal ditulis di samping, bukan diingat samar.",
      "Di visual, balik tanda k dan lihat grafik berbalik dari mati ke meledak.",
    ],
    check: {
      q: "Paruh 2 jam, awal 80, setelah 4 jam?",
      a: "20.",
      why: "Dua kali paruh: 80 → 40 → 20.",
    },
    related: "laplace",
  },
  {
    id: "pde",
    track: "advanced",
    title: "Persamaan diferensial parsial",
    blurb: "Ruang dan waktu bersama-sama. Riley bab 20–21.",
    chapter: "Riley, Hobson & Bence — bab 20 dan 21",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu tahu kenapa syarat batas mengubah nada.",
    oneIdea: "PDB mengikat perubahan terhadap lebih dari satu variabel. Syarat batas memilih jawaban yang benar-benar terjadi, bukan hanya rumus umum.",
    ideas: [
      { t: "Gelombang", d: "∂²u/∂t² = c² ∂²u/∂x². c cepat rambat." },
      { t: "Panas", d: "∂u/∂t = α ∂²u/∂x². Panas menyebar, tidak berayun seperti gelombang ideal." },
      { t: "Ujung tetap", d: "Dawai yang diikat memaksa kelipatan setengah gelombang. λ_n = (nπ/L)² pada pemisahan variabel." },
    ],
    formulas: [
      { name: "Cepat dawai", tex: "c=\\sqrt{T/\\mu}", when: "Masuk ke persamaan gelombang." },
      { name: "Nilai eigen", tex: "\\lambda_n=(n\\pi/L)^2", when: "Ujung tetap. Di latihan, π² boleh diambil 10 jika diperintahkan." },
      { name: "Frekuensi dasar", tex: "f_1=c/(2L)", when: "Setengah gelombang pas sepanjang dawai." },
    ],
    visual: "wave",
    caseTitle: "Nada dasar gitar, sekali lagi secara PDB",
    casePlace: "Fret",
    caseStory: "Menekan fret memperpendek L. Frekuensi dasar c/(2L) naik. Itulah tangga nada, muncul dari syarat batas, bukan dari selera.",
    caseMove: [
      "Ujung jembatan dan fret adalah u = 0.",
      "Bentuk yang muat: setengah gelombang, gelombang penuh, tiga setengah, …",
      "Perpendek L, f1 naik. Harmonic ke-n adalah kelipatan n.",
    ],
    caseTake: "Soal PDB tanpa syarat batas belum selesai. Batas adalah bagian dari fisika.",
    traps: [
      { bad: "f1 = c/L.", fix: "Untuk ujung tetap, panjang gelombang dasar 2L, jadi f = c/(2L)." },
      { bad: "Memakai persamaan panas untuk dawai ideal.", fix: "Dawai ideal: persamaan gelombang, turunan waktu orde dua." },
    ],
    howTo: [
      "Tulis jenis persamaan dalam satu kata: gelombang, panas, atau Laplace.",
      "Gambar ujung dan syaratnya sebelum memisahkan variabel.",
      "Di lab gelombang, hitung berapa panjang gelombang yang muat.",
    ],
    check: {
      q: "c=10 m/s, L=1 m, ujung tetap. Frekuensi dasar?",
      a: "5 Hz.",
      why: "f = c/(2L) = 5.",
    },
    related: "gelombang",
  },
  {
    id: "variasi",
    track: "advanced",
    title: "Kalkulus variasi",
    blurb: "Mencari fungsi, bukan angka. Riley bab 22.",
    chapter: "Riley, Hobson & Bence — bab 22",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu melihat hukum Newton sebagai lintasan yang dipilih.",
    oneIdea: "Kalkulus variasi mencari fungsi yang membuat sebuah integral ekstrem. Cahaya, sabun, dan mekanika sering memilih yang paling hemat.",
    ideas: [
      { t: "Bukan turunan biasa", d: "Yang berubah adalah seluruh bentuk kurva, sedikit." },
      { t: "Euler–Lagrange", d: "Syarat untuk Lagrangian L(t, x, ẋ)." },
      { t: "Kasus datar", d: "Lintasan terpendek di bidang adalah garis lurus. EL mengembalikan y'' = 0." },
    ],
    formulas: [
      { name: "EL", tex: "\\frac{d}{dt}\\frac{\\partial L}{\\partial \\dot x}=\\frac{\\partial L}{\\partial x}", when: "Satu koordinat." },
      { name: "Mekanika", tex: "L=T-V", when: "Energi kinetik dikurangi potensial." },
      { name: "Garis", tex: "y''=0", when: "Meminimalkan panjang di bidang datar." },
    ],
    visual: "variation",
    caseTitle: "Cahaya di atas aspal panas",
    casePlace: "Jalan siang hari",
    caseStory: "Fatamorgana terjadi karena cahaya memilih waktu tempuh minimum, bukan selalu garis geometris, ketika kelajuan cahaya berubah terhadap suhu udara. Itu prinsip Fermat, saudara kalkulus variasi.",
    caseMove: [
      "Jika kelajuan sama di mana-mana, waktu minimum = jarak minimum = garis lurus.",
      "Jika lapisan bawah lebih cepat, jalur yang sedikit melengkung bisa lebih singkat waktunya.",
      "Mata memperpanjang sinar itu lurus, sehingga aspal basah semu muncul.",
    ],
    caseTake: "Yang diekstrimkan harus disebut: panjang, waktu, atau aksi. Jangan berasumsi selalu jarak.",
    traps: [
      { bad: "Mencari angka x yang meminimalkan, padahal yang dicari fungsi y(x).", fix: "Jawabannya sebuah bentuk, atau koefisien bentuk itu." },
      { bad: "∂L/∂ẋ diperlakukan sebagai turunan total sembarangan.", fix: "Turunkan terhadap variabel kecepatan, anggap x independen, baru kemudian d/dt." },
    ],
    howTo: [
      "Tulis apa yang diintegralkan, dalam satu baris.",
      "Untuk mekanika, T dan V dipisah sebelum EL.",
      "Di visual, bandingkan panjang garis dan busur. Garis menang di bidang datar.",
    ],
    check: {
      q: "Jarak terpendek (0,0) ke (3,4)?",
      a: "5.",
      why: "Garis lurus, 3-4-5.",
    },
    related: "ode",
  },
  {
    id: "residu",
    track: "advanced",
    title: "Residu dan Cauchy",
    blurb: "Integral keliling hanya melihat kutub. Riley bab 24.",
    chapter: "Riley, Hobson & Bence — bab 24",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa memutuskan integral tanpa mengintegralkan sepanjang jalan.",
    oneIdea: "Untuk fungsi yang mulus kecuali di kutub, integral keliling sama dengan 2πi kali jumlah residu di dalam kontur.",
    ideas: [
      { t: "Residu", d: "Koefisien 1/(z−a) pada kutub sederhana. Bukan nilai fungsi." },
      { t: "Di luar tidak dihitung", d: "Kutub di luar kontur menyumbang nol." },
      { t: "Arah", d: "Rumus standar berlawanan arah jarum jam." },
    ],
    formulas: [
      { name: "Cauchy", tex: "\\oint f\\,dz = 2\\pi i \\sum \\mathrm{Res}", when: "Kontur tertutup sederhana, arah positif." },
      { name: "Kutub sederhana", tex: "\\mathrm{Res}\\,\\dfrac{c}{z-a}=c", when: "Bentuk paling dasar." },
      { name: "Pembilang mulus", tex: "\\mathrm{Res}\\,\\dfrac{p(z)}{z-a}=p(a)", when: "p tidak nol dan tidak punya kutub di a." },
    ],
    visual: "argand",
    caseTitle: "Integral nyata yang membandel",
    casePlace: "Meja fisika matematis",
    caseStory: "Sejumlah integral dari −∞ sampai ∞ pada fisika gelombang lebih mudah jika dibawa ke bidang kompleks dan ditutup dengan busur besar. Busurnya sering menyumbang nol, dan yang tersisa residu di dalam.",
    caseMove: [
      "Cari kutub.",
      "Buang yang di luar kontur.",
      "Kalikan 2πi dengan jumlah residu yang di dalam. Di latihan awal, sering yang diminta residunya saja.",
    ],
    caseTake: "Sebelum menghitung 2πi, pastikan soalnya meminta integral atau hanya residu.",
    traps: [
      { bad: "Residu = nilai fungsi di kutub.", fix: "Fungsi meledak di kutub. Residu adalah koefisiennya." },
      { bad: "Menghitung kutub di luar.", fix: "Lihat jari-jari kontur." },
    ],
    howTo: [
      "Gambar lingkaran dan titik kutub. Arsir yang di dalam.",
      "Untuk bentuk c/(z−a), residu langsung c. Jangan diolah lagi.",
      "Ucapkan arah: melawan jarum jam.",
    ],
    check: {
      q: "Residu 5/(z−1) di z=1?",
      a: "5.",
      why: "Koefisiennya 5.",
    },
    related: "kompleks",
  },
  {
    id: "numerik",
    track: "advanced",
    title: "Metode numerik",
    blurb: "Jika rumus tertutup tidak ada. Riley bab 27.",
    chapter: "Riley, Hobson & Bence — bab 27",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa melangkah sekali dan tahu seberapa jauh salahnya.",
    oneIdea: "Metode numerik mengganti rumus tertutup dengan langkah berulang. Jawaban tanpa taksiran galat belum selesai.",
    ideas: [
      { t: "Newton", d: "Garis singgung memotong sumbu, itu tebakan berikutnya." },
      { t: "Trapesium", d: "Luasan dihampiri trapesium. Makin halus potongannya, biasanya makin dekat." },
      { t: "Galat", d: "Bandingkan dengan nilai eksak jika ada, bagi nilai eksak, kali 100 untuk persen." },
    ],
    formulas: [
      { name: "Newton", tex: "x_{n+1}=x_n-\\dfrac{f(x_n)}{f'(x_n)}", when: "f' tidak nol." },
      { name: "Trapesium", tex: "\\dfrac{h}{2}(y_0+2y_1+\\cdots+y_n)", when: "Titik berjarak h." },
      { name: "Galat relatif", tex: "\\dfrac{|\\text{hampiran}-\\text{eksak}|}{|\\text{eksak}|}", when: "Eksak diketahui." },
    ],
    visual: "newtonplot",
    caseTitle: "Mencari akar di penerima GPS",
    casePlace: "Ponsel",
    caseStory: "Posisi dari beberapa satelit menghasilkan persamaan yang tidak punya rumus indah. Penerima menjalankan iterasi, berhenti ketika pergeseran lebih kecil daripada ketelitian yang dibutuhkan.",
    caseMove: [
      "Mulai dari tebakan masuk akal, x0.",
      "Satu langkah Newton memberi x1.",
      "Ulangi sampai perubahan kecil. Di latihan, sering hanya satu langkah yang diminta.",
    ],
    caseTake: "Iterasi butuh syarat berhenti. Tanpa itu kamu tidak tahu kapan 'cukup'.",
    traps: [
      { bad: "Membagi f' dengan f.", fix: "Yang dikurangi adalah f/f'." },
      { bad: "Menyebut hampiran trapesium sebagai nilai eksak.", fix: "Sebut hampiran, kecuali kebetulan galatnya nol." },
    ],
    howTo: [
      "Hitung f dan f' di dua baris terpisah.",
      "Satu langkah, satu kotak. Jangan menggabungkan dua iterasi.",
      "Di visual, lihat garis singgung memotong sumbu. Itu x1.",
    ],
    check: {
      q: "f=x²−2, x0=1. x1 Newton?",
      a: "1,5.",
      why: "1 − (1−2)/2 = 1,5.",
    },
    related: "turunan",
  },
  {
    id: "khusus",
    track: "advanced",
    title: "Fungsi khusus",
    blurb: "Legendre untuk bola. Riley bab 18.",
    chapter: "Riley, Hobson & Bence — bab 18",
    minutes: 10,
    level: "lanjut",
    promise: "Nama-nama ini berhenti menjadi hiasan di buku fisika.",
    oneIdea: "Fungsi khusus adalah solusi baku yang terlalu sering muncul sampai diberi nama. Legendre muncul saat bola, Bessel saat silinder.",
    ideas: [
      { t: "Tiga pertama", d: "P0=1, P1=x, P2=(3x²−1)/2." },
      { t: "Di x=1", d: "Semua Pn(1)=1. Cek cepat kalau rumusmu benar." },
      { t: "Kapan dipakai", d: "Bagian sudut atom hidrogen dan potensi di luar bola memakai Legendre." },
    ],
    formulas: [
      { name: "P0 dan P1", tex: "P_0=1,\\quad P_1=x", when: "Derajat rendah." },
      { name: "P2", tex: "P_2=\\dfrac{3x^2-1}{2}", when: "Mulai ada lengkung." },
      { name: "P3", tex: "P_3=\\dfrac{5x^3-3x}{2}", when: "Suku ganjil." },
    ],
    visual: "legendre",
    caseTitle: "Awan elektron, bagian sudut",
    casePlace: "Kimia kuantum pengantar",
    caseStory: "Bentuk orbital bukan hiasan buku. Bagian yang bergantung sudut pada atom hidrogen dibangun dari fungsi Legendre terkait. P2 yang nol di sudut tertentu adalah alasan ada arah 'lobus'.",
    caseMove: [
      "Hitung P2(0) = −1/2.",
      "P2(1) = 1.",
      "Di antara itu fungsi berubah tanda. Perubahan tanda itulah simpul pada pola sudut.",
    ],
    caseTake: "Kamu tidak perlu seluruh teori atom untuk mulai: evaluasi polinomnya dengan benar dulu.",
    traps: [
      { bad: "P2 = 3x² − 1, lupa bagi 2.", fix: "Faktor 1/2 bagian dari definisi." },
      { bad: "P1 = 1.", fix: "P1 = x. P0 yang 1." },
    ],
    howTo: [
      "Hafal P0, P1, P2 saja minggu ini. Cukup.",
      "Selalu cek P(1)=1 setelah menulis rumus.",
      "Geser x di visual dan sebut tanda P2.",
    ],
    check: {
      q: "P2(1)?",
      a: "1.",
      why: "(3−1)/2 = 1. Berlaku untuk semua n.",
    },
    related: "parsial",
  },
  {
    id: "statistik",
    track: "advanced",
    title: "Peluang untuk fisika",
    blurb: "Rata-rata, sebaran, Poisson. Riley bab 30.",
    chapter: "Riley, Hobson & Bence — bab 30",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa berbicara tentang ketidaktahuan dengan angka.",
    oneIdea: "Di fisika, peluang menggambarkan cacahan acak atau ketidaktahuan. Yang dilaporkan biasanya rata-rata dan sebaran, bukan satu nasib.",
    ideas: [
      { t: "Rata-rata", d: "Jumlah bagi banyaknya, untuk data seragam bobotnya." },
      { t: "Varians populasi", d: "Rata-rata kuadrat simpangan. Bagi n jika seluruh populasi ada di tangan." },
      { t: "Poisson", d: "Cacahan langka pada selang tetap: foton, peluruhan, kedatangan. P(0)=e^{−λ}." },
    ],
    formulas: [
      { name: "Rata-rata", tex: "\\langle x\\rangle=\\dfrac{1}{n}\\sum x_i", when: "Data berbobot sama." },
      { name: "Varians populasi", tex: "\\sigma^2=\\dfrac{1}{n}\\sum (x_i-\\langle x\\rangle)^2", when: "Bagi n, bukan n−1." },
      { name: "Poisson nol", tex: "P(0)=e^{-\\lambda}", when: "Tidak ada kejadian." },
    ],
    visual: "poisson",
    caseTitle: "Detektor yang menghitung foton",
    casePlace: "Laboratorium optik",
    caseStory: "Pada cahaya sangat redup, detektor tidak memberi arus mulus. Ia menghitung klik. Jumlah klik pada tiap sekon mengikuti Poisson dengan rata-rata λ.",
    caseMove: [
      "Jika λ = 2, rata-rata dua klik per sekon.",
      "Peluang sekon yang sunyi P(0) = e^{−2} ≈ 0,14.",
      "Sekon sunyi itu bukan detektor rusak. Ia bagian dari sebaran.",
    ],
    caseTake: "Keacakan punya pola pada jumlah besar. Satu pengukuran sepi belum menyanggah rata-rata.",
    traps: [
      { bad: "Bagi n−1 padahal soal meminta populasi.", fix: "Baca pembaginya. Di sini n." },
      { bad: "P(0) = λ.", fix: "P(0) = e^{−λ}. λ adalah rata-rata, bukan peluang nol." },
    ],
    howTo: [
      "Hitung rata-rata sebelum varians. Jangan dilewati.",
      "Untuk Poisson, tulis λ dan k di pojok.",
      "Geser λ di visual: sebaran melebar saat rata-rata naik.",
    ],
    check: {
      q: "Rata-rata 2, 4, 6?",
      a: "4.",
      why: "12/3.",
    },
    related: "peluang",
  },
];

const byId = new Map(topics.map((t) => [t.id, t]));

export function allTopics(): Topic[] {
  return topics;
}

export function getTopic(id: string): Topic | undefined {
  return byId.get(id);
}

export function bankOf(id: string): number {
  return BANK[id] ?? 120;
}

export function bankTotal(): number {
  return topics.reduce((sum, t) => sum + bankOf(t.id), 0);
}

export const TRACKS: { id: TrackId; title: string; kicker: string; note: string }[] = [
  {
    id: "math",
    title: "Dasar matematika",
    kicker: "Fondasi",
    note: "Dari persen sampai integral. Satu ide tiap layar.",
  },
  {
    id: "physics",
    title: "Dasar fisika",
    kicker: "Dunia nyata",
    note: "Gerak, gaya, gelombang, listrik, cahaya, foton.",
  },
  {
    id: "advanced",
    title: "Lanjutan",
    kicker: "Riley, Hobson & Bence",
    note: "Alur bab Mathematical Methods for Physics and Engineering. Penjelasan ditulis ulang supaya singkat, bukan kutipan buku.",
  },
];
