import type { Topic } from "./topics.ts";

/**
 * Materi tambahan untuk menutup celah peta profesi: statistik untuk data, aljabar linear,
 * optimasi, keuangan, logika, kriptografi, informasi, proses acak, kendali, sinyal digital,
 * kuantum, rotasi, panas, magnet, dan kekuatan bahan.
 */
export const EXTRA_TOPICS: Topic[] = [
  {
    id: "rantai",
    track: "math",
    title: "Aturan rantai dan optimasi",
    blurb: "Fungsi bersusun, lalu turun bukit galat.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menurunkan fungsi bersusun dan menjelaskan satu langkah gradient descent.",
    oneIdea:
      "Jika y bergantung pada u dan u bergantung pada x, laju y terhadap x adalah perkalian dua laju: dy/dx = dy/du · du/dx. Optimasi memakai turunan itu untuk melangkah ke arah yang menurunkan galat.",
    analogy:
      "Roda gigi besar memutar roda gigi sedang, yang memutar roda gigi kecil. Jika tiap putaran besar menghasilkan 3 putaran sedang, dan tiap putaran sedang menghasilkan 2 putaran kecil, roda kecil berputar 6 kali. Laju dikalikan sepanjang rantai.",
    ideas: [
      { t: "Aturan kali", d: "(uv)' = u'v + uv'. Dua faktor bergantian diturunkan, yang lain dibiarkan." },
      { t: "Aturan rantai", d: "Turunkan bagian luar, biarkan isinya, lalu kalikan dengan turunan bagian dalam." },
      { t: "Gradient descent", d: "Parameter baru = lama − laju belajar × turunan. Turunan positif berarti mundur, negatif berarti maju." },
    ],
    formulas: [
      { name: "Rantai", tex: "\\dfrac{dy}{dx}=\\dfrac{dy}{du}\\cdot\\dfrac{du}{dx}", when: "Fungsi di dalam fungsi." },
      { name: "Kali", tex: "(uv)'=u'v+uv'", when: "Dua fungsi dikalikan." },
      { name: "Langkah gradien", tex: "w_{\\text{baru}}=w-\\eta\\,\\dfrac{dL}{dw}", when: "η laju belajar. Terlalu besar: melompat-lompat." },
    ],
    visual: "descent",
    caseTitle: "Satu neuron yang belajar",
    casePlace: "Pelatihan model",
    caseStory:
      "Model y = w·x dengan satu data x = 2, target 10. Galat L = (w·x − 10)². Mulai dari w = 3. Ke mana dan seberapa jauh w harus digeser?",
    caseMove: [
      "Rantai: dL/dw = 2(wx − 10) · x.",
      "Di w = 3: 2(6 − 10) · 2 = −16. Negatif, jadi w harus naik.",
      "Dengan η = 0,05: w baru = 3 − 0,05 × (−16) = 3,8. Galat turun dari 16 ke (7,6 − 10)² = 5,76.",
    ],
    caseTake: "Backpropagation adalah aturan rantai yang dijalankan dari keluaran ke masukan, lapis demi lapis.",
    traps: [
      { bad: "Turunan (3x+1)² adalah 2(3x+1).", fix: "Kurang dikali turunan bagian dalam: 2(3x+1) · 3." },
      { bad: "Laju belajar besar selalu lebih cepat.", fix: "Terlalu besar membuat langkah melewati lembah dan galat justru naik." },
    ],
    howTo: [
      "Tulis u = bagian dalam sebelum menurunkan.",
      "Kerjakan dari luar ke dalam, lalu kalikan semua mata rantai.",
      "Di visual, ubah laju belajar dan hitung berapa langkah sampai lembah.",
    ],
    check: { q: "Turunan (2x+1)³?", a: "6(2x+1)².", why: "Luar: 3(2x+1)². Dalam: 2. Kalikan." },
    related: "parsial",
  },
  {
    id: "bunga",
    track: "math",
    title: "Bunga, nilai sekarang, anuitas",
    blurb: "Uang hari ini tidak sama dengan uang tahun depan.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa membandingkan cicilan, tabungan, dan janji pembayaran di waktu yang berbeda.",
    oneIdea:
      "Uang bertumbuh dengan faktor (1+i) tiap periode. Nilai sekarang membalik arah itu: uang masa depan dibagi (1+i)ⁿ. Pembayaran rata berkala adalah deret geometri yang punya rumus ringkas.",
    analogy:
      "Bibit pohon yang ditanam hari ini akan lebih besar tahun depan. Pohon tahun depan dengan ukuran tertentu setara dengan bibit yang lebih kecil hari ini. Nilai sekarang adalah ukuran bibit itu.",
    ideas: [
      { t: "Majemuk", d: "Bunga ikut berbunga. Faktornya dikalikan tiap periode, bukan ditambahkan." },
      { t: "Nilai sekarang", d: "PV = FV / (1+i)ⁿ. Diskonto adalah bunga yang dibalik." },
      { t: "Anuitas", d: "Pembayaran sama tiap periode adalah deret geometri. Rumusnya meringkas penjumlahan bulan demi bulan." },
    ],
    formulas: [
      { name: "Nilai masa depan", tex: "FV=PV(1+i)^n", when: "i bunga per periode, n banyak periode." },
      { name: "Nilai sekarang", tex: "PV=\\dfrac{FV}{(1+i)^n}", when: "Membawa uang masa depan ke hari ini." },
      { name: "Anuitas", tex: "PV=A\\,\\dfrac{1-(1+i)^{-n}}{i}", when: "Pembayaran A di akhir tiap periode." },
    ],
    visual: "pv",
    caseTitle: "Cicilan motor “bunga 1%”",
    casePlace: "Dealer",
    caseStory: "Pinjaman Rp20 juta, bunga 1% per bulan, 24 bulan. Berapa cicilan bulanan yang adil?",
    caseMove: [
      "PV = 20 juta, i = 0,01, n = 24.",
      "Faktor anuitas (1 − 1,01⁻²⁴) / 0,01 ≈ 21,24.",
      "A = 20 juta / 21,24 ≈ Rp942 ribu. Total bayar ≈ Rp22,6 juta.",
    ],
    caseTake: "Bunga 1% per bulan bukan 12% per tahun efektif: 1,01¹² ≈ 1,127, jadi sekitar 12,7%.",
    traps: [
      { bad: "Bunga majemuk n periode = n × bunga.", fix: "Kalikan faktor (1+i) sebanyak n kali." },
      { bad: "Membandingkan uang di waktu berbeda secara langsung.", fix: "Bawa semua ke satu titik waktu, biasanya sekarang, sebelum dibandingkan." },
    ],
    howTo: [
      "Gambar garis waktu: kapan uang masuk, kapan keluar.",
      "Samakan periode: bunga per bulan untuk cicilan bulanan.",
      "Di visual, geser bunga dan lihat nilai sekarang menyusut.",
    ],
    check: { q: "Rp1.100.000 setahun lagi, bunga 10% per tahun. Nilai sekarang?", a: "Rp1.000.000.", why: "1.100.000 / 1,1." },
    related: "barisan",
  },
  {
    id: "sampel",
    track: "math",
    title: "Statistik sampel dan distribusi normal",
    blurb: "Rata-rata, median, simpangan baku, kurva lonceng.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa meringkas data dan tahu kapan satu angka sudah aneh.",
    oneIdea:
      "Satu tabel diringkas oleh pusat (rata-rata, median) dan sebaran (simpangan baku). Banyak data mendekati kurva normal: sekitar 68% dalam 1 simpangan baku dari rata-rata, 95% dalam 2.",
    analogy:
      "Tinggi badan siswa satu sekolah. Kebanyakan berkumpul di sekitar tengah, makin sedikit yang sangat pendek atau sangat tinggi. Bentuknya seperti lonceng. Simpangan baku adalah lebar lonceng itu.",
    ideas: [
      { t: "Median tahan pencilan", d: "Satu gaji direktur menarik rata-rata, tetapi hampir tidak menggeser median." },
      { t: "Sampel bagi n−1", d: "Varians sampel s² membagi n−1 supaya tidak meremehkan sebaran populasi." },
      { t: "Skor z", d: "z = (x − rata-rata) / s. |z| > 2 sudah jarang, |z| > 3 sangat jarang." },
    ],
    formulas: [
      { name: "Varians sampel", tex: "s^2=\\dfrac{1}{n-1}\\sum (x_i-\\bar x)^2", when: "Data adalah sampel dari populasi yang lebih besar." },
      { name: "Skor z", tex: "z=\\dfrac{x-\\bar x}{s}", when: "Seberapa jauh, dalam satuan simpangan baku." },
      { name: "Aturan 68–95–99,7", tex: "P(|z|<1)\\approx0{,}68,\\quad P(|z|<2)\\approx0{,}95", when: "Data mendekati normal." },
    ],
    visual: "normal",
    caseTitle: "Gaji rata-rata yang menyesatkan",
    casePlace: "Laporan HR",
    caseStory: "Sembilan karyawan bergaji Rp5 juta, satu direktur Rp95 juta. Rata-ratanya Rp14 juta, padahal tidak ada yang bergaji dekat angka itu.",
    caseMove: [
      "Rata-rata = (9 × 5 + 95) / 10 = 14 juta.",
      "Median = 5 juta, nilai tengah setelah diurutkan.",
      "Laporkan median dan sebaran, atau pisahkan pencilannya dari ringkasan.",
    ],
    caseTake: "Rata-rata tanpa sebaran dan tanpa median bisa benar secara hitungan, tetapi menipu secara makna.",
    traps: [
      { bad: "Varians sampel dibagi n.", fix: "Untuk sampel, n−1. Bagi n hanya jika seluruh populasi ada di tangan." },
      { bad: "Semua data dianggap normal.", fix: "Gaji, waktu tunggu, dan ukuran klaim sering miring. Lihat histogram dulu." },
    ],
    howTo: [
      "Urutkan data sebelum apa pun: median dan pencilan langsung kelihatan.",
      "Hitung rata-rata, lalu simpangan tiap data, baru kuadratkan.",
      "Di visual, lebarkan σ dan perhatikan rentang 95% ikut melebar.",
    ],
    check: { q: "Rata-rata 70, simpangan baku 10. Skor z untuk nilai 90?", a: "2.", why: "(90 − 70) / 10 = 2. Kira-kira hanya 2,5% data di atasnya." },
    related: "inferensi",
  },
  {
    id: "inferensi",
    track: "math",
    title: "Interval kepercayaan dan uji hipotesis",
    blurb: "Kapan selisih itu nyata, kapan kebetulan sampel.",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa bilang “naik 2%” lengkap dengan seberapa yakin.",
    oneIdea:
      "Rata-rata sampel bergoyang dari sampel ke sampel. Goyangannya, galat baku, mengecil seperti 1/√n. Interval 95% kira-kira rata-rata ± 2 galat baku.",
    analogy:
      "Mencicipi satu sendok sup untuk menebak rasa sepanci. Satu sendok bisa kebetulan asin. Sepuluh sendok dari tempat berbeda memberi tebakan lebih mantap, tetapi tidak sepuluh kali lebih mantap — hanya sekitar tiga kali, karena √10 ≈ 3,2.",
    ideas: [
      { t: "Galat baku", d: "SE = s / √n. Empat kali data, galatnya separuh." },
      { t: "Interval kepercayaan", d: "Prosedur yang, jika diulang, menangkap nilai sebenarnya 95% dari waktu." },
      { t: "Nilai p", d: "Seberapa mengejutkan data jika sebenarnya tidak ada efek. Kecil berarti sulit dijelaskan kebetulan, bukan berarti efeknya besar." },
    ],
    formulas: [
      { name: "Galat baku", tex: "SE=\\dfrac{s}{\\sqrt n}", when: "Ketidakpastian rata-rata sampel." },
      { name: "Interval 95%", tex: "\\bar x\\pm1{,}96\\,SE", when: "Sampel cukup besar." },
      { name: "Proporsi", tex: "SE_p=\\sqrt{\\dfrac{p(1-p)}{n}}", when: "Rasio konversi, persen klik, tingkat cacat." },
    ],
    visual: "ci",
    caseTitle: "Uji A/B tombol beli",
    casePlace: "Toko daring",
    caseStory:
      "Versi A: 1.000 pengunjung, 50 membeli (5,0%). Versi B: 1.000 pengunjung, 62 membeli (6,2%). Apakah B benar-benar lebih baik?",
    caseMove: [
      "SE proporsi A ≈ √(0,05 × 0,95 / 1000) ≈ 0,0069. SE B ≈ 0,0076.",
      "SE selisih ≈ √(0,0069² + 0,0076²) ≈ 0,0103. Selisih 0,012 hanya sekitar 1,2 SE.",
      "Di bawah 2 SE: belum meyakinkan. Kumpulkan data lebih banyak sebelum mengumumkan pemenang.",
    ],
    caseTake: "Selisih kecil pada sampel kecil adalah noise sampai terbukti sebaliknya.",
    traps: [
      { bad: "p = 0,03 berarti 3% peluang hipotesis nol benar.", fix: "Nilai p dihitung dengan menganggap hipotesis nol benar. Ia bukan peluang hipotesis itu." },
      { bad: "Dua kali data, galat separuhnya.", fix: "Galat turun seperti 1/√n. Butuh empat kali data untuk separuh." },
    ],
    howTo: [
      "Tulis n, rata-rata atau proporsi, dan s sebelum rumus.",
      "Selalu laporkan interval, bukan hanya angka tengah.",
      "Di visual, naikkan n dan lihat interval menyempit pelan.",
    ],
    check: { q: "s = 20, n = 100. Galat baku rata-rata?", a: "2.", why: "20 / √100 = 20 / 10." },
    related: "regresi",
  },
  {
    id: "regresi",
    track: "math",
    title: "Korelasi dan regresi linear",
    blurb: "Garis terbaik yang melewati awan titik.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa membaca kemiringan regresi dan tidak tertipu korelasi.",
    oneIdea:
      "Regresi linear mencari garis ŷ = a + bx yang membuat jumlah kuadrat galat vertikal sekecil mungkin. Korelasi r mengukur seberapa rapat titik di sekitar garis, dari −1 sampai 1.",
    analogy:
      "Remah roti di meja tersebar memanjang miring. Kamu meletakkan sebatang lidi supaya jarak remah ke lidi sekecil mungkin. Lidi itu garis regresi. Kalau remahnya membentuk bulatan, lidi mana pun sama buruknya: korelasinya nol.",
    ideas: [
      { t: "Kemiringan", d: "b = kovarians / varians x. Satuannya: satuan y per satuan x." },
      { t: "Korelasi", d: "r tanpa satuan. r² adalah porsi variasi y yang dijelaskan garis." },
      { t: "Bukan sebab", d: "Penjualan es krim dan kasus tenggelam naik bersama karena musim panas, bukan saling menyebabkan." },
    ],
    formulas: [
      { name: "Kemiringan", tex: "b=\\dfrac{\\sum (x_i-\\bar x)(y_i-\\bar y)}{\\sum (x_i-\\bar x)^2}", when: "Kuadrat terkecil." },
      { name: "Intersep", tex: "a=\\bar y-b\\,\\bar x", when: "Garis selalu lewat titik rata-rata." },
      { name: "Prediksi", tex: "\\hat y=a+bx", when: "Hanya di dalam rentang data." },
    ],
    visual: "scatter",
    caseTitle: "Iklan dan penjualan",
    casePlace: "Rapat pemasaran",
    caseStory: "Lima bulan data: biaya iklan (juta) 1, 2, 3, 4, 5 dan penjualan (juta) 12, 14, 18, 20, 21.",
    caseMove: [
      "Rata-rata x = 3, rata-rata y = 17.",
      "Σ(x−x̄)(y−ȳ) = 10 + 3 + 0 + 3 + 8 = 24. Σ(x−x̄)² = 10. Jadi b = 2,4.",
      "a = 17 − 2,4 × 3 = 9,8. Tiap tambahan 1 juta iklan diikuti kira-kira 2,4 juta penjualan — dalam data ini, bukan janji sebab-akibat.",
    ],
    caseTake: "Kemiringan menjawab “berapa per satuan”. Ia tidak menjawab “kenapa”.",
    traps: [
      { bad: "Korelasi tinggi berarti sebab-akibat.", fix: "Cari variabel ketiga dan arah waktu. Eksperimen acak yang menjawab sebab." },
      { bad: "Memprediksi jauh di luar rentang data.", fix: "Garis hanya teruji di tempat datanya ada." },
    ],
    howTo: [
      "Gambar titiknya dulu. Hubungan melengkung tidak cocok dengan garis lurus.",
      "Buat tabel x−x̄ dan y−ȳ, baru kalikan.",
      "Di visual, tambah noise dan lihat r turun walau kemiringannya mirip.",
    ],
    check: { q: "Garis ŷ = 9,8 + 2,4x. Prediksi untuk x = 6?", a: "24,2.", why: "9,8 + 14,4. Hati-hati: x = 6 sudah di luar data 1–5." },
    related: "sampel",
  },
  {
    id: "bayes",
    track: "math",
    title: "Peluang bersyarat dan Bayes",
    blurb: "Memperbarui keyakinan setelah ada bukti.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa membaca hasil tes, filter spam, dan alarm tanpa panik.",
    oneIdea:
      "Peluang bersyarat P(A|B) mengecilkan dunia ke kasus B saja. Bayes membalik arah: dari P(bukti | sebab) ke P(sebab | bukti), dan angka dasar ikut menentukan.",
    analogy:
      "Di stasiun, kamu melihat orang membawa payung. Apakah sedang hujan? Payung lebih sering dibawa saat hujan, tetapi di kota yang jarang hujan kebanyakan pembawa payung hanya berjaga-jaga. Bukti yang sama berbobot beda, tergantung seberapa sering hujan.",
    ideas: [
      { t: "Kecilkan dunia", d: "P(A|B): hitung hanya di antara kasus yang B." },
      { t: "Angka dasar", d: "Kejadian langka tetap langka setelah bukti yang lemah." },
      { t: "Pikirkan 1.000 orang", d: "Ubah persen jadi jumlah orang. Bayes menjadi pembagian biasa." },
    ],
    formulas: [
      { name: "Bersyarat", tex: "P(A\\mid B)=\\dfrac{P(A\\cap B)}{P(B)}", when: "P(B) tidak nol." },
      { name: "Bayes", tex: "P(A\\mid B)=\\dfrac{P(B\\mid A)\\,P(A)}{P(B)}", when: "Membalik arah syarat." },
      { name: "Peluang total", tex: "P(B)=P(B\\mid A)P(A)+P(B\\mid \\neg A)P(\\neg A)", when: "Penyebut Bayes." },
    ],
    visual: "bayes",
    caseTitle: "Filter spam",
    casePlace: "Kotak masuk",
    caseStory: "20% email adalah spam. Kata “gratis” muncul di 60% spam dan 5% email biasa. Email baru memuat “gratis”. Seberapa mungkin spam?",
    caseMove: [
      "Dari 1.000 email: 200 spam, 800 biasa.",
      "“Gratis” di spam: 120. Di email biasa: 40.",
      "P(spam | gratis) = 120 / 160 = 0,75.",
    ],
    caseTake: "Satu kata menaikkan dugaan dari 20% ke 75%. Kata kedua memperbarui lagi, mulai dari 75%.",
    traps: [
      { bad: "P(A|B) sama dengan P(B|A).", fix: "Peluang sakit jika positif berbeda dari peluang positif jika sakit." },
      { bad: "Mengabaikan angka dasar.", fix: "Selalu mulai dari seberapa sering kejadian itu sebelum ada bukti." },
    ],
    howTo: [
      "Ubah semua persen ke 1.000 kasus.",
      "Gambar tabel 2×2: sebab ya/tidak, bukti ya/tidak.",
      "Di visual, turunkan prevalensi dan lihat nilai prediksi positif runtuh.",
    ],
    check: {
      q: "Dari 1.000 orang, 10 sakit (semua positif) dan 50 orang sehat positif palsu. Peluang sakit jika positif?",
      a: "1/6 ≈ 0,17.",
      why: "10 dari 60 hasil positif.",
    },
    related: "peluang",
  },
  {
    id: "diskrit",
    track: "math",
    title: "Logika, himpunan, dan graf",
    blurb: "Benar-salah, irisan, dan titik yang terhubung.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa membaca kondisi if, menghitung irisan, dan melihat jaringan sebagai graf.",
    oneIdea:
      "Logika menggabungkan pernyataan benar-salah dengan DAN, ATAU, TIDAK. Himpunan menghitung isi kelompok tanpa menghitung dua kali. Graf memodelkan apa pun yang terhubung: jalan, jaringan komputer, pertemanan.",
    analogy:
      "Lampu kamar yang menyala jika saklar pintu ATAU saklar ranjang ditekan berbeda dengan brankas yang terbuka hanya jika kunci DAN sidik jari cocok. Komputer hanya tahu dua keadaan, dan perangkat lunak adalah susunan saklar seperti ini.",
    ideas: [
      { t: "Tabel kebenaran", d: "n pernyataan punya 2ⁿ baris kemungkinan. Tulis semuanya, jangan menebak." },
      { t: "Inklusi-eksklusi", d: "|A ∪ B| = |A| + |B| − |A ∩ B|. Irisan dikurangi sekali." },
      { t: "Derajat graf", d: "Jumlah semua derajat = 2 × banyak sisi, karena tiap sisi punya dua ujung." },
    ],
    formulas: [
      { name: "Gabungan", tex: "|A\\cup B|=|A|+|B|-|A\\cap B|", when: "Dua kelompok yang tumpang tindih." },
      { name: "Implikasi", tex: "p\\Rightarrow q\\ \\equiv\\ \\neg p\\lor q", when: "Salah hanya jika p benar dan q salah." },
      { name: "Jabat tangan", tex: "\\sum_v \\deg(v)=2|E|", when: "Graf tak berarah." },
    ],
    visual: "logic",
    caseTitle: "Survei pemakaian fitur",
    casePlace: "Tim produk",
    caseStory: "Dari 100 responden, 60 memakai fitur chat, 45 memakai fitur bayar, 25 memakai keduanya. Berapa yang tidak memakai keduanya?",
    caseMove: [
      "Chat ∪ bayar = 60 + 45 − 25 = 80.",
      "Yang memakai minimal satu fitur: 80 orang.",
      "Tidak memakai keduanya: 100 − 80 = 20.",
    ],
    caseTake: "Menjumlahkan dua kelompok yang tumpang tindih tanpa mengurangi irisan menghitung orang yang sama dua kali.",
    traps: [
      { bad: "p ⇒ q sama dengan q ⇒ p.", fix: "Hujan ⇒ jalan basah, tetapi jalan basah tidak berarti hujan." },
      { bad: "|A ∪ B| = |A| + |B|.", fix: "Hanya jika A dan B tidak beririsan." },
    ],
    howTo: [
      "Untuk logika, tulis tabel kebenaran lengkap.",
      "Untuk himpunan, gambar diagram Venn dan isi irisan lebih dulu.",
      "Di visual, ubah p dan q, lalu baca keempat operator.",
    ],
    check: { q: "Graf punya 6 sisi. Jumlah semua derajat titiknya?", a: "12.", why: "Tiap sisi menyumbang 2 derajat." },
    related: "modular",
  },
  {
    id: "rotasi",
    track: "physics",
    title: "Gerak melingkar dan rotasi",
    blurb: "Kecepatan sudut, gaya ke pusat, dan torsi.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menghitung putaran roda, gaya di tikungan, dan torsi motor.",
    oneIdea:
      "Setiap besaran gerak lurus punya padanan putar: sudut untuk posisi, ω untuk kecepatan, torsi untuk gaya, momen inersia untuk massa. Benda yang bergerak melingkar butuh gaya yang menarik ke pusat.",
    analogy:
      "Di komidi putar, kuda di pinggir bergerak lebih cepat daripada kuda di dekat poros, walau keduanya berputar satu kali dalam waktu yang sama. Kecepatan sudutnya sama, kecepatan linearnya berbeda.",
    ideas: [
      { t: "Sudut ke linear", d: "v = ωr. Makin jauh dari poros, makin cepat." },
      { t: "Sentripetal", d: "a = v²/r ke arah pusat. Tikungan tajam dan cepat butuh gaya besar." },
      { t: "Torsi", d: "τ = rF sin θ. Gaya yang sama di lengan lebih panjang memutar lebih kuat." },
    ],
    formulas: [
      { name: "Kecepatan linear", tex: "v=\\omega r", when: "ω dalam rad/s." },
      { name: "Percepatan sentripetal", tex: "a_c=\\dfrac{v^2}{r}=\\omega^2 r", when: "Arah ke pusat lingkaran." },
      { name: "Newton rotasi", tex: "\\tau=I\\alpha", when: "I momen inersia: massa versi putar." },
    ],
    visual: "rotation",
    caseTitle: "Motor di tikungan",
    casePlace: "Jalan raya",
    caseStory: "Motor 150 kg (dengan pengendara) melaju 10 m/s di tikungan berjari-jari 20 m. Berapa gaya ke pusat yang harus disediakan gesekan ban?",
    caseMove: [
      "a = v²/r = 100/20 = 5 m/s².",
      "F = m a = 150 × 5 = 750 N.",
      "Gesek maksimum μmg dengan μ = 0,7 adalah 1.050 N: aman. Pada 15 m/s butuh 1.687,5 N: ban tergelincir.",
    ],
    caseTake: "Kecepatan dikuadratkan: naik 50% kecepatan, gaya tikungan naik 125%.",
    traps: [
      { bad: "Gaya sentripetal mendorong ke luar.", fix: "Ia gaya ke dalam yang disediakan gesek, tali, atau gravitasi. Rasa terlempar keluar adalah inersia." },
      { bad: "Memakai derajat per detik pada v = ωr.", fix: "ω harus dalam radian per detik. Satu putaran = 2π rad." },
    ],
    howTo: [
      "Ubah rpm ke rad/s dulu: ω = rpm × 2π / 60.",
      "Gambar arah gaya ke pusat sebelum menghitung.",
      "Di visual, ubah jari-jari dan kecepatan, lalu lihat gaya sentripetal berubah kuadrat.",
    ],
    check: { q: "ω = 4 rad/s, r = 0,5 m. Kecepatan linear?", a: "2 m/s.", why: "v = ωr = 4 × 0,5." },
    related: "newton",
  },
  {
    id: "termo",
    track: "physics",
    title: "Suhu, kalor, dan termodinamika",
    blurb: "Energi panas, perubahan wujud, efisiensi mesin.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menghitung energi pemanas dan tahu kenapa mesin panas tidak bisa 100% efisien.",
    oneIdea:
      "Kalor adalah energi yang pindah karena beda suhu. Menaikkan suhu butuh Q = mcΔT. Hukum pertama: energi dalam berubah karena kalor masuk dikurangi kerja keluar. Hukum kedua membatasi efisiensi mesin panas.",
    analogy:
      "Segelas air panas di meja yang dingin. Panas selalu mengalir dari gelas ke meja, tidak pernah sebaliknya dengan sendirinya. Mesin panas seperti kincir yang memanen sebagian aliran itu; sisanya pasti terbuang ke tempat dingin.",
    ideas: [
      { t: "Kalor jenis", d: "c air ≈ 4.200 J/kg°C. Air lambat panas, makanya radiator memakai air." },
      { t: "Kalor laten", d: "Saat mencair atau mendidih, kalor masuk tetapi suhu diam." },
      { t: "Kelvin", d: "Rumus efisiensi memakai kelvin: K = °C + 273." },
    ],
    formulas: [
      { name: "Kalor", tex: "Q=mc\\,\\Delta T", when: "Tanpa perubahan wujud." },
      { name: "Hukum I", tex: "\\Delta U=Q-W", when: "Q masuk positif, W kerja yang dilakukan sistem." },
      { name: "Carnot", tex: "\\eta_{\\text{maks}}=1-\\dfrac{T_c}{T_h}", when: "Suhu dalam kelvin." },
    ],
    visual: "heat",
    caseTitle: "Pemanas air listrik",
    casePlace: "Kamar mandi",
    caseStory: "Pemanas 2.000 W memanaskan 50 kg air dari 25°C ke 45°C. Berapa lama, jika semua energi masuk ke air?",
    caseMove: [
      "Q = 50 × 4.200 × 20 = 4.200.000 J.",
      "t = Q / P = 4.200.000 / 2.000 = 2.100 s = 35 menit.",
      "Nyatanya lebih lama karena sebagian panas bocor lewat dinding tangki.",
    ],
    caseTake: "Air butuh energi besar untuk panas. Itu sebabnya pemanas air termasuk pemakai listrik terbesar di rumah.",
    traps: [
      { bad: "Memakai °C dalam efisiensi Carnot.", fix: "Ubah ke kelvin: 27°C = 300 K." },
      { bad: "Suhu naik terus selama dipanaskan.", fix: "Saat berubah wujud suhu tetap; kalor dipakai untuk memutus ikatan." },
    ],
    howTo: [
      "Tulis m, c, ΔT lengkap dengan satuannya.",
      "Untuk efisiensi, tulis Th dan Tc dalam kelvin di baris pertama.",
      "Di visual, dekatkan suhu dingin ke suhu panas dan lihat efisiensi maksimum jatuh.",
    ],
    check: { q: "Th = 600 K, Tc = 300 K. Efisiensi Carnot?", a: "50%.", why: "1 − 300/600 = 0,5." },
    related: "energi",
  },
  {
    id: "magnet",
    track: "physics",
    title: "Magnet dan induksi",
    blurb: "Arus membuat gaya, medan yang berubah membuat arus.",
    minutes: 14,
    level: "menengah",
    promise: "Kamu bisa menjelaskan motor listrik, generator, dan trafo charger.",
    oneIdea:
      "Arus listrik di dalam medan magnet mengalami gaya: itu motor. Fluks magnet yang berubah membangkitkan tegangan: itu generator dan trafo (hukum Faraday).",
    analogy:
      "Menggerakkan magnet keluar-masuk kumparan seperti memompa: hanya saat bergerak ada aliran. Magnet yang diam di dalam kumparan, sekuat apa pun, tidak menghasilkan arus. Yang dihitung adalah perubahan, bukan keberadaan.",
    ideas: [
      { t: "Gaya pada kawat", d: "F = BIL sin θ. Kawat yang sejajar medan tidak didorong." },
      { t: "Fluks", d: "Φ = BA cos θ: berapa banyak medan menembus kumparan." },
      { t: "Faraday dan Lenz", d: "Tegangan = −N ΔΦ/Δt. Tanda minus: arus induksi melawan perubahan penyebabnya." },
    ],
    formulas: [
      { name: "Gaya Lorentz kawat", tex: "F=BIL\\sin\\theta", when: "Motor, pengeras suara." },
      { name: "Faraday", tex: "\\varepsilon=-N\\dfrac{\\Delta\\Phi}{\\Delta t}", when: "Generator, induksi." },
      { name: "Trafo ideal", tex: "\\dfrac{V_s}{V_p}=\\dfrac{N_s}{N_p}", when: "Arus bolak-balik." },
    ],
    visual: "induction",
    caseTitle: "Charger ponsel",
    casePlace: "Stopkontak",
    caseStory: "Listrik rumah 220 V AC, ponsel butuh sekitar 5 V. Trafo menurunkan tegangan dengan perbandingan lilitan.",
    caseMove: [
      "Vs/Vp = 5/220 = 1/44.",
      "Jika primer 880 lilitan, sekunder 20 lilitan.",
      "Daya ideal sama, jadi arus sekunder 44 kali arus primer. Charger modern memakai trafo kecil berfrekuensi tinggi, tetapi prinsipnya tetap Faraday.",
    ],
    caseTake: "Trafo hanya bekerja pada arus bolak-balik, karena butuh fluks yang terus berubah.",
    traps: [
      { bad: "Magnet yang diam di dalam kumparan menghasilkan arus.", fix: "Butuh perubahan fluks: gerak, putaran, atau arus yang berubah." },
      { bad: "Trafo penaik tegangan juga menaikkan daya.", fix: "Tegangan naik, arus turun. Daya ideal tetap; nyatanya sedikit hilang jadi panas." },
    ],
    howTo: [
      "Tulis apa yang berubah: B, A, atau sudut.",
      "Untuk trafo, tulis perbandingan lilitan sebagai pecahan dulu.",
      "Di visual, ubah lilitan dan lihat tegangan sekunder.",
    ],
    check: { q: "Primer 1.000 lilitan pada 220 V, sekunder 100 lilitan. Tegangan sekunder?", a: "22 V.", why: "220 × 100 / 1.000." },
    related: "listrik",
  },
  {
    id: "bahan",
    track: "physics",
    title: "Statika dan kekuatan bahan",
    blurb: "Benda diam, tegangan, regangan, faktor keamanan.",
    minutes: 12,
    level: "menengah",
    promise: "Kamu bisa memeriksa apakah batang, baut, atau tuas sederhana kuat menahan beban.",
    oneIdea:
      "Benda diam berarti jumlah gaya dan jumlah torsi sama dengan nol. Kekuatan bahan tidak ditentukan oleh gaya saja, tetapi oleh gaya per luas penampang: tegangan.",
    analogy:
      "Berdiri di lantai kayu dengan sepatu biasa terasa aman, tetapi sepatu hak runcing bisa melubanginya. Beratmu sama, luas tumpuannya beda. Bahan merasakan gaya per luas, bukan gaya total.",
    ideas: [
      { t: "Dua syarat", d: "ΣF = 0 dan Στ = 0. Pilih titik putar yang menghapus gaya yang belum diketahui." },
      { t: "Tegangan dan regangan", d: "σ = F/A dalam pascal. ε = ΔL/L tanpa satuan." },
      { t: "Modulus Young", d: "E = σ/ε. Baja ≈ 200 GPa, jauh lebih kaku daripada aluminium ≈ 70 GPa." },
    ],
    formulas: [
      { name: "Kesetimbangan", tex: "\\sum F=0,\\quad \\sum\\tau=0", when: "Benda diam atau bergerak lurus tetap." },
      { name: "Tegangan", tex: "\\sigma=\\dfrac{F}{A}", when: "Gaya tegak lurus penampang." },
      { name: "Hooke bahan", tex: "\\sigma=E\\,\\varepsilon", when: "Masih di daerah elastis." },
    ],
    visual: "stress",
    caseTitle: "Batang gantungan papan nama",
    casePlace: "Depan toko",
    caseStory: "Papan nama 200 kg digantung pada satu batang baja berpenampang 1 cm². Tegangan luluh baja sekitar 250 MPa. Amankah?",
    caseMove: [
      "F = 200 × 10 = 2.000 N. A = 1 cm² = 0,0001 m².",
      "σ = 2.000 / 0,0001 = 20.000.000 Pa = 20 MPa.",
      "250 / 20 = 12,5: faktor keamanan besar. Aman, kecuali ada karat, retak, atau beban kejut.",
    ],
    caseTake: "Insinyur tidak berhenti di “cukup kuat”. Mereka menyebut faktor keamanannya.",
    traps: [
      { bad: "1 cm² = 10⁻² m².", fix: "1 cm = 10⁻² m, jadi 1 cm² = 10⁻⁴ m²." },
      { bad: "Memilih titik putar sembarang lalu tersesat di aljabar.", fix: "Pilih titik tempat gaya yang belum diketahui bekerja; torsinya nol." },
    ],
    howTo: [
      "Gambar diagram benda bebas lengkap dengan jarak tiap gaya.",
      "Tulis ΣF dan Στ terpisah, satu baris untuk tiap persamaan.",
      "Di visual, kecilkan penampang dan lihat tegangan melonjak.",
    ],
    check: { q: "Gaya 1.000 N pada penampang 0,001 m². Tegangan dalam MPa?", a: "1 MPa.", why: "1.000 / 0,001 = 1.000.000 Pa = 1 MPa." },
    related: "newton",
  },
  {
    id: "linalg",
    track: "advanced",
    title: "Aljabar linear: transformasi dan eigen",
    blurb: "Matriks sebagai mesin peregang, dan arah yang tidak berbelok.",
    chapter: "Lanjutan — aljabar linear terapan",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa membaca perkalian matriks sebagai transformasi dan menemukan nilai eigen 2×2.",
    oneIdea:
      "Matriks kali vektor memindahkan setiap titik bidang. Kebanyakan arah ikut berbelok, tetapi ada arah istimewa yang hanya diregangkan: vektor eigen, dengan faktor regang yang disebut nilai eigen.",
    analogy:
      "Adonan roti yang ditarik ke kanan-kiri. Hampir semua kismis berpindah ke arah baru, tetapi kismis di sepanjang garis tarikan hanya menjauh di garis yang sama. Garis itu arah eigen; seberapa jauh ia meregang adalah nilai eigennya.",
    ideas: [
      { t: "Baris kali kolom", d: "Tiap komponen hasil = satu baris matriks dikali vektor, lalu dijumlah." },
      { t: "Komposisi", d: "AB berarti lakukan B dulu, baru A. Urutan penting." },
      { t: "Eigen 2×2", d: "Av = λv. Nilai λ memenuhi λ² − (a+d)λ + (ad − bc) = 0." },
    ],
    formulas: [
      { name: "Eigen", tex: "A\\mathbf v=\\lambda\\mathbf v", when: "Arah yang hanya diregangkan." },
      { name: "Persamaan karakteristik", tex: "\\lambda^2-(\\operatorname{tr}A)\\,\\lambda+\\det A=0", when: "Matriks 2×2." },
      { name: "Atensi", tex: "\\operatorname{softmax}\\!\\left(\\dfrac{QK^{\\top}}{\\sqrt d}\\right)V", when: "Inti transformer: perkalian matriks dan softmax." },
    ],
    visual: "transform",
    caseTitle: "PCA pada data tinggi-berat",
    casePlace: "Analisis data",
    caseStory:
      "Data tinggi dan berat badan membentuk awan miring. Matriks kovariansnya punya dua vektor eigen: satu searah awan (ukuran tubuh), satu tegak lurus (bentuk tubuh).",
    caseMove: [
      "Kovarians contoh: [[4, 2], [2, 3]].",
      "tr = 7, det = 8, jadi λ² − 7λ + 8 = 0: λ ≈ 5,56 dan 1,44.",
      "Arah eigen pertama memuat 5,56/7 ≈ 79% variasi. Satu sumbu baru meringkas dua kolom.",
    ],
    caseTake: "PCA, PageRank, dan getaran jembatan bertanya hal yang sama: arah mana yang tidak berbelok.",
    traps: [
      { bad: "AB = BA.", fix: "Putar lalu cerminkan berbeda dari cerminkan lalu putar." },
      { bad: "Nilai eigen selalu dibaca dari diagonal.", fix: "Hanya untuk matriks diagonal atau segitiga. Lainnya, selesaikan persamaan karakteristik." },
    ],
    howTo: [
      "Tulis matriks dan vektor berdampingan, tunjuk barisnya dengan jari.",
      "Untuk eigen 2×2, hitung trace dan determinan dulu.",
      "Di visual, ubah entri matriks dan cari arah yang tidak berputar.",
    ],
    check: { q: "Nilai eigen [[3, 0], [0, 5]]?", a: "3 dan 5.", why: "Matriks diagonal: nilai eigennya ada di diagonal." },
    related: "matriks",
  },
  {
    id: "modular",
    track: "advanced",
    title: "Teori bilangan dan aritmetika modular",
    blurb: "Jam, sisa bagi, dan rahasia RSA.",
    chapter: "Lanjutan — dasar kriptografi",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa menghitung sisa bagi pangkat besar dan memahami kenapa RSA aman.",
    oneIdea:
      "Aritmetika modular hanya peduli sisa bagi, seperti jam yang kembali ke nol. Perkalian dan pangkat bisa dikerjakan sambil terus mengambil sisa. Kriptografi memakai operasi yang mudah satu arah tetapi sulit dibalik.",
    analogy:
      "Jam dinding: 10 jam setelah pukul 9 adalah pukul 7, bukan 19. Jam hanya ingat sisa bagi 12. Mencampur cat juga mudah satu arah; memisahkan dua warna yang sudah tercampur hampir mustahil.",
    ideas: [
      { t: "Sisa bagi", d: "a mod n = sisa a dibagi n. 17 mod 5 = 2." },
      { t: "FPB dan Euclid", d: "FPB(a, b) = FPB(b, a mod b), diulang sampai sisanya nol." },
      { t: "Pangkat modular", d: "Kuadratkan berulang dan ambil sisa tiap langkah; angkanya tidak pernah meledak." },
    ],
    formulas: [
      { name: "Kongruen", tex: "a\\equiv b \\pmod n", when: "a dan b bersisa sama jika dibagi n." },
      { name: "Euclid", tex: "\\gcd(a,b)=\\gcd(b,\\ a \\bmod b)", when: "Mencari FPB dengan cepat." },
      { name: "RSA", tex: "c=m^e \\bmod n,\\quad m=c^d \\bmod n", when: "n = pq, p dan q prima rahasia." },
    ],
    visual: "clock",
    caseTitle: "RSA mainan",
    casePlace: "Kelas kriptografi",
    caseStory:
      "p = 3, q = 11, jadi n = 33 dan φ = 20. Kunci publik e = 3, kunci privat d = 7, karena 3 × 7 = 21 ≡ 1 (mod 20). Pesan m = 4.",
    caseMove: [
      "Enkripsi: c = 4³ mod 33 = 64 mod 33 = 31.",
      "Dekripsi: 31⁷ mod 33. Karena 31 ≡ −2, hasilnya (−2)⁷ = −128 ≡ −128 + 132 = 4.",
      "Pesan kembali 4. Di dunia nyata n punya ratusan digit, dan memfaktorkannya yang sulit.",
    ],
    caseTake: "Keamanan RSA bersandar pada satu ketimpangan: mengalikan dua prima itu mudah, memfaktorkan hasilnya sangat sulit.",
    traps: [
      { bad: "Menghitung 7¹⁰⁰ dulu baru diambil sisanya.", fix: "Ambil sisa di setiap langkah; hasilnya sama dan angkanya tetap kecil." },
      { bad: "Sisa bilangan negatif dibiarkan negatif.", fix: "Tambahkan n sampai hasilnya di antara 0 dan n−1." },
    ],
    howTo: [
      "Tulis tabel pangkat dan sisanya sampai polanya berulang.",
      "Untuk FPB, tulis baris Euclid satu per satu.",
      "Di visual, ubah modulus dan lihat jarum kembali ke nol.",
    ],
    check: { q: "2⁵ mod 7?", a: "4.", why: "32 = 4 × 7 + 4." },
    related: "diskrit",
  },
  {
    id: "entropi",
    track: "advanced",
    title: "Entropi dan teori informasi",
    blurb: "Berapa bit untuk sebuah kejutan.",
    chapter: "Lanjutan — teori informasi",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa menghitung entropi dan membaca cross-entropy loss.",
    oneIdea:
      "Informasi sebuah kejadian adalah −log₂ p bit: makin jarang, makin mengejutkan. Entropi adalah rata-rata kejutan itu. Cross-entropy mengukur kejutan jika kamu memakai tebakan q padahal kenyataannya p.",
    analogy:
      "Tebak angka 1 sampai 8 dengan pertanyaan ya/tidak. Tiga pertanyaan selalu cukup: belah dua, belah dua, belah dua. Itu tiga bit. Kalau satu angka hampir selalu muncul, rata-rata kamu butuh lebih sedikit pertanyaan — entropinya lebih kecil.",
    ideas: [
      { t: "Satuan bit", d: "Satu pilihan dari dua yang sama mungkin = 1 bit." },
      { t: "Entropi maksimum", d: "Sebaran yang rata membuat entropi terbesar: log₂ n." },
      { t: "Cross-entropy", d: "Loss klasifikasi = −log peluang yang diberikan model ke jawaban yang benar." },
    ],
    formulas: [
      { name: "Informasi", tex: "I=-\\log_2 p", when: "Satu kejadian berpeluang p." },
      { name: "Entropi", tex: "H=-\\sum_i p_i\\log_2 p_i", when: "Rata-rata kejutan." },
      { name: "Cross-entropy", tex: "H(p,q)=-\\sum_i p_i\\ln q_i", when: "Loss model klasifikasi." },
    ],
    visual: "entropy",
    caseTitle: "Loss model yang ragu",
    casePlace: "Pelatihan klasifikasi",
    caseStory: "Sebuah gambar kucing. Model A memberi peluang “kucing” 0,9. Model B memberi 0,5. Cross-entropy memakai log natural.",
    caseMove: [
      "Loss A = −ln 0,9 ≈ 0,105.",
      "Loss B = −ln 0,5 ≈ 0,693.",
      "Model yang yakin dan benar dihukum kecil. Yang yakin tetapi salah (misal 0,01) dihukum −ln 0,01 ≈ 4,6.",
    ],
    caseTake: "Cross-entropy menghukum keyakinan yang salah jauh lebih keras daripada keraguan.",
    traps: [
      { bad: "Entropi koin adil = 0,5 bit.", fix: "1 bit: −2 × 0,5 × log₂ 0,5 = 1." },
      { bad: "Peluang 0 dari model dianggap aman.", fix: "−log 0 tak hingga. Model memberi peluang kecil, bukan nol." },
    ],
    howTo: [
      "Ingat log₂ 2 = 1, log₂ 4 = 2, log₂ 8 = 3.",
      "Untuk entropi, buat kolom p, −log₂ p, lalu kalikan dan jumlahkan.",
      "Di visual, geser p koin dan lihat puncak entropi di 0,5.",
    ],
    check: { q: "Entropi dadu adil 8 sisi?", a: "3 bit.", why: "log₂ 8 = 3." },
    related: "bayes",
  },
  {
    id: "stokastik",
    track: "advanced",
    title: "Proses stokastik dan random walk",
    blurb: "Langkah acak yang menumpuk menjadi pola.",
    chapter: "Lanjutan — proses acak",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa menaksir seberapa jauh harga atau partikel menyimpang setelah banyak langkah acak.",
    oneIdea:
      "Random walk menjumlahkan langkah acak. Rata-ratanya bisa tetap di nol, tetapi sebarannya tumbuh seperti √n. Rantai Markov: keadaan berikutnya hanya bergantung pada keadaan sekarang.",
    analogy:
      "Orang yang berjalan sempoyongan di gang: tiap langkah ke kiri atau kanan secara acak. Rata-rata ia tidak ke mana-mana, tetapi makin lama ia makin mungkin jauh dari titik awal — bukan sebanding waktu, melainkan akar waktu.",
    ideas: [
      { t: "Akar n", d: "Simpangan baku setelah n langkah ±1 adalah √n." },
      { t: "Volatilitas", d: "Di keuangan, risiko setahun ≈ risiko harian × √252 hari bursa." },
      { t: "Markov", d: "Tabel peluang pindah. Kalikan berulang untuk melihat beberapa langkah ke depan." },
    ],
    formulas: [
      { name: "Sebaran", tex: "\\sigma_n=\\sigma\\sqrt n", when: "Langkah independen." },
      { name: "Harapan", tex: "E[S_n]=n\\mu", when: "μ rata-rata satu langkah." },
      { name: "Markov", tex: "\\pi_{t+1}=\\pi_t P", when: "P matriks transisi, baris berjumlah 1." },
    ],
    visual: "walk",
    caseTitle: "Volatilitas saham tahunan",
    casePlace: "Meja analis",
    caseStory: "Return harian sebuah saham punya simpangan baku 1%. Berapa kira-kira simpangan baku setahun (252 hari bursa)?",
    caseMove: [
      "Anggap return harian independen.",
      "σ tahunan ≈ 1% × √252 ≈ 1% × 15,9 ≈ 15,9%.",
      "Bukan 252%. Risiko tumbuh dengan akar waktu, karena hari naik dan hari turun saling menutup.",
    ],
    caseTake: "Ketidakpastian menumpuk, tetapi lebih lambat dari intuisi: akar, bukan garis.",
    traps: [
      { bad: "Sebaran n langkah = n × sebaran satu langkah.", fix: "Varians yang dijumlah, bukan simpangan baku. Simpangan baku tumbuh √n." },
      { bad: "Setelah lima kali merah, hitam “sudah waktunya”.", fix: "Langkah independen tidak punya ingatan. Itu kekeliruan penjudi." },
    ],
    howTo: [
      "Tulis μ dan σ satu langkah sebelum menskalakan.",
      "Untuk Markov, tulis matriks transisi dan cek tiap baris berjumlah 1.",
      "Di visual, acak ulang beberapa kali dan lihat jarak akhir menyebar seperti √n.",
    ],
    check: { q: "Random walk ±1, 100 langkah. Simpangan baku posisi akhir?", a: "10.", why: "√100 = 10." },
    related: "statistik",
  },
  {
    id: "kendali",
    track: "advanced",
    title: "Sistem kendali dan umpan balik",
    blurb: "Ukur, bandingkan, koreksi. Berulang.",
    chapter: "Lanjutan — teknik kendali",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa menjelaskan kerja PID dan kenapa kendali P saja menyisakan galat.",
    oneIdea:
      "Kendali umpan balik mengukur keluaran, membandingkannya dengan target, lalu memberi koreksi. P bereaksi pada galat sekarang, I pada tumpukan galat masa lalu, D pada laju perubahan galat.",
    analogy:
      "Menyetir di jalan lurus: kalau mobil menyimpang ke kiri, kamu memutar ke kanan sebanding jauhnya simpangan (P). Kalau angin terus mendorong, kamu menahan setir sedikit terus-menerus (I). Kalau mobil cepat bergeser, kamu bereaksi lebih awal (D).",
    ideas: [
      { t: "Galat", d: "e = target − ukuran. Semua kendali dimulai dari sini." },
      { t: "P saja", d: "Untuk plant sederhana, galat tunak = 1/(1 + K). K besar mengecilkan galat tetapi bisa berosilasi." },
      { t: "Konstanta waktu", d: "Sistem orde satu mencapai 63% target setelah satu τ, dan sekitar 98% setelah 4τ." },
    ],
    formulas: [
      { name: "PID", tex: "u=K_p e+K_i\\int e\\,dt+K_d\\dfrac{de}{dt}", when: "Pengendali paling umum di industri." },
      { name: "Galat tunak P", tex: "e_{ss}=\\dfrac{1}{1+K}", when: "Plant berpenguatan 1, masukan tangga satuan." },
      { name: "Orde satu", tex: "y(t)=1-e^{-t/\\tau}", when: "Respons terhadap tangga satuan." },
    ],
    visual: "pid",
    caseTitle: "Termostat AC",
    casePlace: "Ruang kerja",
    caseStory: "Target 24°C, ruangan 30°C. Kendali P saja dengan penguatan total K = 4.",
    caseMove: [
      "Galat tunak relatif = 1/(1 + 4) = 0,2.",
      "Dari selisih 6°C tersisa 0,2 × 6 = 1,2°C: ruangan tertahan di 25,2°C.",
      "Tambahkan suku I: tumpukan galat terus mendorong sampai galatnya nol.",
    ],
    caseTake: "P memberi kecepatan, I menghapus sisa galat, D meredam ayunan.",
    traps: [
      { bad: "Penguatan makin besar selalu makin baik.", fix: "Terlalu besar membuat sistem berosilasi atau bahkan tidak stabil." },
      { bad: "Suku integral menghapus galat seketika.", fix: "I butuh waktu dan bisa membuat lonjakan (overshoot)." },
    ],
    howTo: [
      "Tulis target, ukuran, dan galat lengkap dengan tandanya.",
      "Ubah satu penguatan dalam satu waktu.",
      "Di visual, naikkan Kp dan lihat sisa galat mengecil, lalu tambahkan Ki.",
    ],
    check: { q: "Kendali P dengan K = 9. Galat tunak relatif?", a: "0,1.", why: "1/(1 + 9)." },
    related: "laplace",
  },
  {
    id: "sinyal",
    track: "advanced",
    title: "Sinyal digital dan sampling",
    blurb: "Dari gelombang ke angka, tanpa kehilangan nada.",
    chapter: "Lanjutan — pemrosesan sinyal digital",
    minutes: 12,
    level: "lanjut",
    promise: "Kamu bisa memilih laju sampling dan memprediksi aliasing.",
    oneIdea:
      "Sinyal analog dicuplik tiap 1/fs detik. Supaya frekuensi f tidak menyamar, fs harus lebih dari 2f (Nyquist). Tiap cuplikan dibulatkan ke salah satu dari 2ⁿ tingkat untuk n bit.",
    analogy:
      "Roda mobil di video kadang tampak berputar mundur. Kamera memotret terlalu jarang dibanding putaran roda, sehingga gambar berurutan menangkap posisi yang menipu. Itu aliasing.",
    ideas: [
      { t: "Nyquist", d: "fs > 2 f_maks. Audio CD 44,1 kHz menangkap sampai 22,05 kHz, di atas batas dengar." },
      { t: "Alias", d: "Frekuensi f yang dicuplik fs tampak sebagai |f − k·fs| yang terdekat ke nol." },
      { t: "Resolusi DFT", d: "N cuplikan pada fs memberi jarak frekuensi fs/N." },
    ],
    formulas: [
      { name: "Nyquist", tex: "f_s>2f_{\\text{maks}}", when: "Syarat tanpa aliasing." },
      { name: "Alias", tex: "f_a=|f-k f_s|", when: "k bulat yang membuat f_a ≤ fs/2." },
      { name: "Kuantisasi", tex: "L=2^n", when: "n bit per cuplikan." },
    ],
    visual: "sampling",
    caseTitle: "Sensor getaran yang menipu",
    casePlace: "Pabrik",
    caseStory: "Motor berputar menghasilkan getaran 900 Hz. Sensor murah mencuplik 1.000 kali per detik.",
    caseMove: [
      "Nyquist butuh fs > 1.800 Hz. 1.000 Hz terlalu rendah.",
      "Alias: |900 − 1 × 1.000| = 100 Hz.",
      "Data terlihat seperti getaran 100 Hz yang pelan. Diagnosisnya salah, padahal masalahnya di laju sampling.",
    ],
    caseTake: "Aliasing tidak bisa diperbaiki setelah dicuplik. Saring frekuensi tinggi sebelum sampling.",
    traps: [
      { bad: "fs = 2f sudah cukup.", fix: "Harus lebih dari 2f; dalam praktik 2,5 sampai 10 kali." },
      { bad: "Menambah bit menambah frekuensi yang bisa ditangkap.", fix: "Bit menambah ketelitian amplitudo. Frekuensi ditentukan fs." },
    ],
    howTo: [
      "Tulis frekuensi maksimum sinyal sebelum memilih fs.",
      "Untuk alias, kurangi kelipatan fs sampai hasilnya di bawah fs/2.",
      "Di visual, turunkan fs dan lihat titik cuplik membentuk gelombang palsu.",
    ],
    check: { q: "ADC 10 bit. Berapa tingkat kuantisasi?", a: "1.024.", why: "2¹⁰ = 1.024." },
    related: "fourier",
  },
  {
    id: "kuantum",
    track: "advanced",
    title: "Mekanika kuantum dasar",
    blurb: "Amplitudo, pengukuran, dan qubit.",
    chapter: "Lanjutan — fisika dan komputasi kuantum",
    minutes: 14,
    level: "lanjut",
    promise: "Kamu bisa menghitung peluang hasil ukur sebuah qubit dan tahu kenapa n qubit memuat 2ⁿ amplitudo.",
    oneIdea:
      "Keadaan kuantum ditulis sebagai amplitudo. Peluang hasil ukur adalah kuadrat besar amplitudo, dan jumlahnya harus 1. Sebelum diukur, qubit boleh berada dalam superposisi |0⟩ dan |1⟩; pengukuran memilih salah satu.",
    analogy:
      "Koin yang sedang berputar di meja bukan “diam-diam sudah angka” atau “sudah gambar”. Begitu ditepuk, hasilnya satu sisi. Bedanya, amplitudo kuantum bisa saling menghapus seperti gelombang, dan itulah sumber kekuatan komputer kuantum.",
    ideas: [
      { t: "Normalisasi", d: "|α|² + |β|² = 1." },
      { t: "Banyak qubit", d: "n qubit punya 2ⁿ amplitudo sekaligus. 50 qubit: lebih dari satu kuadriliun." },
      { t: "Tingkat energi", d: "Elektron dalam kotak hanya boleh berenergi Eₙ = n²E₁. Loncatan antartingkat memancarkan foton." },
    ],
    formulas: [
      { name: "Qubit", tex: "|\\psi\\rangle=\\alpha|0\\rangle+\\beta|1\\rangle", when: "Superposisi dua keadaan." },
      { name: "Aturan Born", tex: "P(0)=|\\alpha|^2,\\quad P(1)=|\\beta|^2", when: "Saat diukur." },
      { name: "de Broglie", tex: "\\lambda=\\dfrac{h}{p}", when: "Partikel sebagai gelombang." },
    ],
    visual: "qubit",
    caseTitle: "Qubit setelah gerbang Hadamard",
    casePlace: "Komputer kuantum",
    caseStory: "Qubit mulai di |0⟩. Gerbang Hadamard membuatnya (|0⟩ + |1⟩)/√2.",
    caseMove: [
      "α = β = 1/√2 ≈ 0,707.",
      "P(0) = P(1) = 0,707² = 0,5.",
      "Hadamard kedua membuat amplitudo |1⟩ saling menghapus: qubit kembali ke |0⟩ dengan peluang 1. Koin biasa tidak bisa begitu.",
    ],
    caseTake: "Peluang kuantum datang dari amplitudo yang bisa saling menguatkan atau menghapus — bukan sekadar ketidaktahuan.",
    traps: [
      { bad: "Peluang = amplitudo.", fix: "Peluang = kuadrat besar amplitudo." },
      { bad: "Superposisi berarti qubit diam-diam sudah 0 atau 1.", fix: "Interferensi membuktikan tidak. Hasil ditentukan saat diukur." },
    ],
    howTo: [
      "Selalu cek |α|² + |β|² = 1 dulu.",
      "Untuk n qubit, tulis 2ⁿ sebelum menggambar apa pun.",
      "Di visual, putar sudut qubit dan lihat peluang 0 dan 1 bertukar.",
    ],
    check: { q: "α = 0,6 dan β nyata positif. Berapa P(1)?", a: "0,64.", why: "P(0) = 0,36, jadi P(1) = 1 − 0,36." },
    related: "kompleks",
  },
];
