/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as RumusRouteImport } from './routes/rumus'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BelajarTopicIdRouteImport } from './routes/belajar.$topicId'
import { Route as LatihanTopicIdRouteImport } from './routes/latihan.$topicId'
import { Route as PetaIndexRouteImport } from './routes/peta.index'
import { Route as PetaRoleIdRouteImport } from './routes/peta.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const RumusRoute = RumusRouteImport.update({
  id: '/rumus',
  path: '/rumus',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarTopicIdRoute = BelajarTopicIdRouteImport.update({
  id: '/belajar/$topicId',
  path: '/belajar/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanTopicIdRoute = LatihanTopicIdRouteImport.update({
  id: '/latihan/$topicId',
  path: '/latihan/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaIndexRoute = PetaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetaRoute,
} as any)
const PetaRoleIdRoute = PetaRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => PetaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/peta': typeof PetaRouteWithChildren
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/peta/': typeof PetaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/peta': typeof PetaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metode': typeof MetodeRoute
  '/peta': typeof PetaRouteWithChildren
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/peta/': typeof PetaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metode'
    | '/peta'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/latihan/$topicId'
    | '/peta/$roleId'
    | '/peta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metode'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/latihan/$topicId'
    | '/peta/$roleId'
    | '/peta'
  id:
    | '__root__'
    | '/'
    | '/metode'
    | '/peta'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/latihan/$topicId'
    | '/peta/$roleId'
    | '/peta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetodeRoute: typeof MetodeRoute
  PetaRoute: typeof PetaRouteWithChildren
  RumusRoute: typeof RumusRoute
  StudioRoute: typeof StudioRoute
  BelajarTopicIdRoute: typeof BelajarTopicIdRoute
  LatihanTopicIdRoute: typeof LatihanTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rumus': {
      id: '/rumus'
      path: '/rumus'
      fullPath: '/rumus'
      preLoaderRoute: typeof RumusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/$topicId': {
      id: '/belajar/$topicId'
      path: '/belajar/$topicId'
      fullPath: '/belajar/$topicId'
      preLoaderRoute: typeof BelajarTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan/$topicId': {
      id: '/latihan/$topicId'
      path: '/latihan/$topicId'
      fullPath: '/latihan/$topicId'
      preLoaderRoute: typeof LatihanTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta/': {
      id: '/peta/'
      path: '/'
      fullPath: '/peta/'
      preLoaderRoute: typeof PetaIndexRouteImport
      parentRoute: typeof PetaRoute
    }
    '/peta/$roleId': {
      id: '/peta/$roleId'
      path: '/$roleId'
      fullPath: '/peta/$roleId'
      preLoaderRoute: typeof PetaRoleIdRouteImport
      parentRoute: typeof PetaRoute
    }
  }
}

interface PetaRouteChildren {
  PetaRoleIdRoute: typeof PetaRoleIdRoute
  PetaIndexRoute: typeof PetaIndexRoute
}

const PetaRouteChildren: PetaRouteChildren = {
  PetaRoleIdRoute: PetaRoleIdRoute,
  PetaIndexRoute: PetaIndexRoute,
}

const PetaRouteWithChildren = PetaRoute._addFileChildren(PetaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetodeRoute: MetodeRoute,
  PetaRoute: PetaRouteWithChildren,
  RumusRoute: RumusRoute,
  StudioRoute: StudioRoute,
  BelajarTopicIdRoute: BelajarTopicIdRoute,
  LatihanTopicIdRoute: LatihanTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
