/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetodeRouteImport } from './routes/metode'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as RumusRouteImport } from './routes/rumus'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as BelajarTopicIdRouteImport } from './routes/belajar.$topicId'
import { Route as KodeIndexRouteImport } from './routes/kode.index'
import { Route as KodeLessonIdRouteImport } from './routes/kode.$lessonId'
import { Route as LatihanTopicIdRouteImport } from './routes/latihan.$topicId'
import { Route as LpdpIndexRouteImport } from './routes/lpdp.index'
import { Route as LpdpSubRouteImport } from './routes/lpdp.$sub'
import { Route as LpdpEsaiRouteImport } from './routes/lpdp.esai'
import { Route as LpdpSimulasiRouteImport } from './routes/lpdp.simulasi'
import { Route as LpdpWawancaraRouteImport } from './routes/lpdp.wawancara'
import { Route as PetaIndexRouteImport } from './routes/peta.index'
import { Route as PetaRoleIdRouteImport } from './routes/peta.$roleId'
import { Route as ProyekIndexRouteImport } from './routes/proyek.index'
import { Route as ProyekProjectIdRouteImport } from './routes/proyek.$projectId'
import { Route as RuangIndexRouteImport } from './routes/ruang.index'
import { Route as RuangRoomIdRouteImport } from './routes/ruang.$roomId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as KodeTantanganIndexRouteImport } from './routes/kode.tantangan.index'
import { Route as KodeTantanganChallengeIdRouteImport } from './routes/kode.tantangan.$challengeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodeRoute = MetodeRouteImport.update({
  id: '/metode',
  path: '/metode',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const RumusRoute = RumusRouteImport.update({
  id: '/rumus',
  path: '/rumus',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarTopicIdRoute = BelajarTopicIdRouteImport.update({
  id: '/belajar/$topicId',
  path: '/belajar/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeIndexRoute = KodeIndexRouteImport.update({
  id: '/kode/',
  path: '/kode/',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeLessonIdRoute = KodeLessonIdRouteImport.update({
  id: '/kode/$lessonId',
  path: '/kode/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LatihanTopicIdRoute = LatihanTopicIdRouteImport.update({
  id: '/latihan/$topicId',
  path: '/latihan/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LpdpIndexRoute = LpdpIndexRouteImport.update({
  id: '/lpdp/',
  path: '/lpdp/',
  getParentRoute: () => rootRouteImport,
} as any)
const LpdpSubRoute = LpdpSubRouteImport.update({
  id: '/lpdp/$sub',
  path: '/lpdp/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const LpdpEsaiRoute = LpdpEsaiRouteImport.update({
  id: '/lpdp/esai',
  path: '/lpdp/esai',
  getParentRoute: () => rootRouteImport,
} as any)
const LpdpSimulasiRoute = LpdpSimulasiRouteImport.update({
  id: '/lpdp/simulasi',
  path: '/lpdp/simulasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LpdpWawancaraRoute = LpdpWawancaraRouteImport.update({
  id: '/lpdp/wawancara',
  path: '/lpdp/wawancara',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaIndexRoute = PetaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetaRoute,
} as any)
const PetaRoleIdRoute = PetaRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => PetaRoute,
} as any)
const ProyekIndexRoute = ProyekIndexRouteImport.update({
  id: '/proyek/',
  path: '/proyek/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyekProjectIdRoute = ProyekProjectIdRouteImport.update({
  id: '/proyek/$projectId',
  path: '/proyek/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const RuangIndexRoute = RuangIndexRouteImport.update({
  id: '/ruang/',
  path: '/ruang/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuangRoomIdRoute = RuangRoomIdRouteImport.update({
  id: '/ruang/$roomId',
  path: '/ruang/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeTantanganIndexRoute = KodeTantanganIndexRouteImport.update({
  id: '/kode/tantangan/',
  path: '/kode/tantangan/',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeTantanganChallengeIdRoute =
  KodeTantanganChallengeIdRouteImport.update({
    id: '/kode/tantangan/$challengeId',
    path: '/kode/tantangan/$challengeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metode': typeof MetodeRoute
  '/peta': typeof PetaRouteWithChildren
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/kode/$lessonId': typeof KodeLessonIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/lpdp/$sub': typeof LpdpSubRoute
  '/lpdp/esai': typeof LpdpEsaiRoute
  '/lpdp/simulasi': typeof LpdpSimulasiRoute
  '/lpdp/wawancara': typeof LpdpWawancaraRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/proyek/$projectId': typeof ProyekProjectIdRoute
  '/ruang/$roomId': typeof RuangRoomIdRoute
  '/kode/': typeof KodeIndexRoute
  '/lpdp/': typeof LpdpIndexRoute
  '/peta/': typeof PetaIndexRoute
  '/proyek/': typeof ProyekIndexRoute
  '/ruang/': typeof RuangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kode/tantangan/$challengeId': typeof KodeTantanganChallengeIdRoute
  '/kode/tantangan/': typeof KodeTantanganIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metode': typeof MetodeRoute
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/kode/$lessonId': typeof KodeLessonIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/lpdp/$sub': typeof LpdpSubRoute
  '/lpdp/esai': typeof LpdpEsaiRoute
  '/lpdp/simulasi': typeof LpdpSimulasiRoute
  '/lpdp/wawancara': typeof LpdpWawancaraRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/proyek/$projectId': typeof ProyekProjectIdRoute
  '/ruang/$roomId': typeof RuangRoomIdRoute
  '/kode': typeof KodeIndexRoute
  '/lpdp': typeof LpdpIndexRoute
  '/peta': typeof PetaIndexRoute
  '/proyek': typeof ProyekIndexRoute
  '/ruang': typeof RuangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kode/tantangan/$challengeId': typeof KodeTantanganChallengeIdRoute
  '/kode/tantangan': typeof KodeTantanganIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metode': typeof MetodeRoute
  '/peta': typeof PetaRouteWithChildren
  '/rumus': typeof RumusRoute
  '/studio': typeof StudioRoute
  '/belajar/$topicId': typeof BelajarTopicIdRoute
  '/kode/$lessonId': typeof KodeLessonIdRoute
  '/latihan/$topicId': typeof LatihanTopicIdRoute
  '/lpdp/$sub': typeof LpdpSubRoute
  '/lpdp/esai': typeof LpdpEsaiRoute
  '/lpdp/simulasi': typeof LpdpSimulasiRoute
  '/lpdp/wawancara': typeof LpdpWawancaraRoute
  '/peta/$roleId': typeof PetaRoleIdRoute
  '/proyek/$projectId': typeof ProyekProjectIdRoute
  '/ruang/$roomId': typeof RuangRoomIdRoute
  '/kode/': typeof KodeIndexRoute
  '/lpdp/': typeof LpdpIndexRoute
  '/peta/': typeof PetaIndexRoute
  '/proyek/': typeof ProyekIndexRoute
  '/ruang/': typeof RuangIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/kode/tantangan/$challengeId': typeof KodeTantanganChallengeIdRoute
  '/kode/tantangan/': typeof KodeTantanganIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/metode'
    | '/peta'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/kode/$lessonId'
    | '/latihan/$topicId'
    | '/lpdp/$sub'
    | '/lpdp/esai'
    | '/lpdp/simulasi'
    | '/lpdp/wawancara'
    | '/peta/$roleId'
    | '/proyek/$projectId'
    | '/ruang/$roomId'
    | '/kode/'
    | '/lpdp/'
    | '/peta/'
    | '/proyek/'
    | '/ruang/'
    | '/api/auth/$'
    | '/kode/tantangan/$challengeId'
    | '/kode/tantangan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/metode'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/kode/$lessonId'
    | '/latihan/$topicId'
    | '/lpdp/$sub'
    | '/lpdp/esai'
    | '/lpdp/simulasi'
    | '/lpdp/wawancara'
    | '/peta/$roleId'
    | '/proyek/$projectId'
    | '/ruang/$roomId'
    | '/kode'
    | '/lpdp'
    | '/peta'
    | '/proyek'
    | '/ruang'
    | '/api/auth/$'
    | '/kode/tantangan/$challengeId'
    | '/kode/tantangan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/metode'
    | '/peta'
    | '/rumus'
    | '/studio'
    | '/belajar/$topicId'
    | '/kode/$lessonId'
    | '/latihan/$topicId'
    | '/lpdp/$sub'
    | '/lpdp/esai'
    | '/lpdp/simulasi'
    | '/lpdp/wawancara'
    | '/peta/$roleId'
    | '/proyek/$projectId'
    | '/ruang/$roomId'
    | '/kode/'
    | '/lpdp/'
    | '/peta/'
    | '/proyek/'
    | '/ruang/'
    | '/api/auth/$'
    | '/kode/tantangan/$challengeId'
    | '/kode/tantangan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MetodeRoute: typeof MetodeRoute
  PetaRoute: typeof PetaRouteWithChildren
  RumusRoute: typeof RumusRoute
  StudioRoute: typeof StudioRoute
  BelajarTopicIdRoute: typeof BelajarTopicIdRoute
  KodeLessonIdRoute: typeof KodeLessonIdRoute
  LatihanTopicIdRoute: typeof LatihanTopicIdRoute
  LpdpSubRoute: typeof LpdpSubRoute
  LpdpEsaiRoute: typeof LpdpEsaiRoute
  LpdpSimulasiRoute: typeof LpdpSimulasiRoute
  LpdpWawancaraRoute: typeof LpdpWawancaraRoute
  ProyekProjectIdRoute: typeof ProyekProjectIdRoute
  RuangRoomIdRoute: typeof RuangRoomIdRoute
  KodeIndexRoute: typeof KodeIndexRoute
  LpdpIndexRoute: typeof LpdpIndexRoute
  ProyekIndexRoute: typeof ProyekIndexRoute
  RuangIndexRoute: typeof RuangIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  KodeTantanganChallengeIdRoute: typeof KodeTantanganChallengeIdRoute
  KodeTantanganIndexRoute: typeof KodeTantanganIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metode': {
      id: '/metode'
      path: '/metode'
      fullPath: '/metode'
      preLoaderRoute: typeof MetodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rumus': {
      id: '/rumus'
      path: '/rumus'
      fullPath: '/rumus'
      preLoaderRoute: typeof RumusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar/$topicId': {
      id: '/belajar/$topicId'
      path: '/belajar/$topicId'
      fullPath: '/belajar/$topicId'
      preLoaderRoute: typeof BelajarTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode/': {
      id: '/kode/'
      path: '/kode'
      fullPath: '/kode/'
      preLoaderRoute: typeof KodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode/$lessonId': {
      id: '/kode/$lessonId'
      path: '/kode/$lessonId'
      fullPath: '/kode/$lessonId'
      preLoaderRoute: typeof KodeLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latihan/$topicId': {
      id: '/latihan/$topicId'
      path: '/latihan/$topicId'
      fullPath: '/latihan/$topicId'
      preLoaderRoute: typeof LatihanTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpdp/': {
      id: '/lpdp/'
      path: '/lpdp'
      fullPath: '/lpdp/'
      preLoaderRoute: typeof LpdpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpdp/$sub': {
      id: '/lpdp/$sub'
      path: '/lpdp/$sub'
      fullPath: '/lpdp/$sub'
      preLoaderRoute: typeof LpdpSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpdp/esai': {
      id: '/lpdp/esai'
      path: '/lpdp/esai'
      fullPath: '/lpdp/esai'
      preLoaderRoute: typeof LpdpEsaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpdp/simulasi': {
      id: '/lpdp/simulasi'
      path: '/lpdp/simulasi'
      fullPath: '/lpdp/simulasi'
      preLoaderRoute: typeof LpdpSimulasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpdp/wawancara': {
      id: '/lpdp/wawancara'
      path: '/lpdp/wawancara'
      fullPath: '/lpdp/wawancara'
      preLoaderRoute: typeof LpdpWawancaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta/': {
      id: '/peta/'
      path: '/'
      fullPath: '/peta/'
      preLoaderRoute: typeof PetaIndexRouteImport
      parentRoute: typeof PetaRoute
    }
    '/peta/$roleId': {
      id: '/peta/$roleId'
      path: '/$roleId'
      fullPath: '/peta/$roleId'
      preLoaderRoute: typeof PetaRoleIdRouteImport
      parentRoute: typeof PetaRoute
    }
    '/proyek/': {
      id: '/proyek/'
      path: '/proyek'
      fullPath: '/proyek/'
      preLoaderRoute: typeof ProyekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyek/$projectId': {
      id: '/proyek/$projectId'
      path: '/proyek/$projectId'
      fullPath: '/proyek/$projectId'
      preLoaderRoute: typeof ProyekProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruang/': {
      id: '/ruang/'
      path: '/ruang'
      fullPath: '/ruang/'
      preLoaderRoute: typeof RuangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruang/$roomId': {
      id: '/ruang/$roomId'
      path: '/ruang/$roomId'
      fullPath: '/ruang/$roomId'
      preLoaderRoute: typeof RuangRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode/tantangan/': {
      id: '/kode/tantangan/'
      path: '/kode/tantangan'
      fullPath: '/kode/tantangan/'
      preLoaderRoute: typeof KodeTantanganIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode/tantangan/$challengeId': {
      id: '/kode/tantangan/$challengeId'
      path: '/kode/tantangan/$challengeId'
      fullPath: '/kode/tantangan/$challengeId'
      preLoaderRoute: typeof KodeTantanganChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PetaRouteChildren {
  PetaRoleIdRoute: typeof PetaRoleIdRoute
  PetaIndexRoute: typeof PetaIndexRoute
}

const PetaRouteChildren: PetaRouteChildren = {
  PetaRoleIdRoute: PetaRoleIdRoute,
  PetaIndexRoute: PetaIndexRoute,
}

const PetaRouteWithChildren = PetaRoute._addFileChildren(PetaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MetodeRoute: MetodeRoute,
  PetaRoute: PetaRouteWithChildren,
  RumusRoute: RumusRoute,
  StudioRoute: StudioRoute,
  BelajarTopicIdRoute: BelajarTopicIdRoute,
  KodeLessonIdRoute: KodeLessonIdRoute,
  LatihanTopicIdRoute: LatihanTopicIdRoute,
  LpdpSubRoute: LpdpSubRoute,
  LpdpEsaiRoute: LpdpEsaiRoute,
  LpdpSimulasiRoute: LpdpSimulasiRoute,
  LpdpWawancaraRoute: LpdpWawancaraRoute,
  ProyekProjectIdRoute: ProyekProjectIdRoute,
  RuangRoomIdRoute: RuangRoomIdRoute,
  KodeIndexRoute: KodeIndexRoute,
  LpdpIndexRoute: LpdpIndexRoute,
  ProyekIndexRoute: ProyekIndexRoute,
  RuangIndexRoute: RuangIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  KodeTantanganChallengeIdRoute: KodeTantanganChallengeIdRoute,
  KodeTantanganIndexRoute: KodeTantanganIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
